import type { Rule } from './itemRules';

export type ItemRole='offense'|'defense'|'utility';
export interface ExpansionItem {
  id:string; name:string; description:string; flavor:string; rarity:number;
  role:ItemRole; rule:Rule; cursed?:boolean;
}
export const EXPANSION_ITEMS:ExpansionItem[] = [
  {id:'stolen_wallet',name:'CARTERA ROBADA',description:'+20% migajas de enemigos.',flavor:'Si preguntan, ya venía vacía.',rarity:1,role:'utility',rule:{currencyScale:.2}},
  {id:'reinforced_loaf',name:'PAN DE CAJA REFORZADO',description:'+1 vida máxima.',flavor:'La resistencia viene rebanada.',rarity:1,role:'defense',rule:{maxHearts:1}},
  {id:'spring_feather',name:'PLUMA CON RESORTE',description:'+20% distancia del esquive.',flavor:'Aprobada por ningún ingeniero.',rarity:2,role:'utility',rule:{dashDistance:.2}},
  {id:'pirate_sneakers',name:'TENIS PIRATA',description:'+15% velocidad de movimiento.',flavor:'Parecen originales desde lejos.',rarity:1,role:'utility',rule:{speed:.15}},
  {id:'oxxo_coffee',name:'CAFÉ DEL OXXO',description:'+20% cadencia de disparo. -5% precisión.',flavor:'Dormir era opcional.',rarity:2,role:'offense',rule:{fireRate:.2,accuracy:.05}},
  {id:'crumpled_receipt',name:'RECIBO ARRUGADO',description:'Las compras cuestan 8% menos.',flavor:'Todavía se alcanza a leer.',rarity:1,role:'utility',rule:{shop:-.08}},
  {id:'cloned_card',name:'TARJETA CLONADA',description:'Primera compra de cada piso: -50%.',flavor:'El titular no está enterado.',rarity:3,role:'utility',rule:{firstDiscount:.5}},
  {id:'mint_gum',name:'CHICLE DE MENTA',description:'Tras esquivar: +15% velocidad durante 2 s.',flavor:'Aliento fresco, expediente sucio.',rarity:1,role:'utility',rule:{dashHaste:.15}},
  {id:'motorcycle_helmet',name:'CASCO DE MOTOCICLISTA',description:'El primer golpe de cada sala causa 50% menos daño.',flavor:'La moto se quedó afuera.',rarity:2,role:'defense',rule:{firstHitReduction:.5}},
  {id:'lucky_crumbs',name:'MIGAJAS DE LA SUERTE',description:'+8% probabilidad de encontrar objetos raros.',flavor:'No las barras.',rarity:1,role:'utility',rule:{rarityLuck:.08}},
  {id:'stolen_backpack',name:'MOCHILA ROBADA',description:'+8 migajas al entrar a cada piso.',flavor:'Traía lunch y antecedentes.',rarity:1,role:'utility',rule:{floorCrumbs:8}},
  {id:'chocolate_bread',name:'PAN CON CHOCOLATE',description:'Al recuperar vida: +20% daño durante 5 s.',flavor:'Consuelo con consecuencias.',rarity:2,role:'offense',rule:{chocolate:.2}},
  {id:'titanium_beak',name:'PICO DE TITANIO',description:'+1 penetración de proyectil.',flavor:'Abre todo menos cuentas legales.',rarity:2,role:'offense',rule:{penetration:1}},
  {id:'polarized_glasses',name:'LENTES POLARIZADOS',description:'+10% probabilidad de golpe crítico.',flavor:'Ve directo al problema.',rarity:2,role:'offense',rule:{crit:.1}},
  {id:'copper_feather',name:'PLUMA DE COBRE',description:'Los golpes críticos tienen 20% de soltar una migaja.',flavor:'Hasta el cobre deja ganancia.',rarity:2,role:'utility',rule:{critCoinChance:.2}},
  {id:'wet_socks',name:'CALCETINES MOJADOS',description:'Dejas charcos al caminar. Enemigos: -25% velocidad.',flavor:'El peor día, la mejor trampa.',rarity:1,role:'defense',rule:{wetSocks:.25}},
  {id:'bouncing_egg',name:'HUEVO REBOTADOR',description:'Cada quinto proyectil gana un rebote.',flavor:'No lo intentes en la cocina.',rarity:2,role:'offense',rule:{fifthBounce:1}},
  {id:'goalkeeper_gloves',name:'GUANTES DE PORTERO',description:'Al esquivar: 20% de reflejar cada proyectil cercano.',flavor:'Atajada del año.',rarity:2,role:'defense',rule:{reflectChance:.2}},
  {id:'grandma_container',name:'TUPPER DE LA ABUELA',description:'25% de conservar la comida al recogerla.',flavor:'El recipiente sí se devuelve.',rarity:3,role:'defense',rule:{keepFood:.25}},
  {id:'hard_bolillo',name:'BOLILLO DURO',description:'+2 daño. -8% cadencia de disparo.',flavor:'Arma blanca si le echas ganas.',rarity:2,role:'offense',rule:{damage:2,fireRate:-.08}},
  {id:'bank_blueprint',name:'PLANO DEL BANCO',description:'Revela las salas conectadas a las ya descubiertas.',flavor:'Dice dónde está la salida. Casi.',rarity:2,role:'utility',rule:{blueprint:1}},
  {id:'stolen_gps',name:'GPS ROBADO',description:'Marca rutas conocidas a tienda, jefe y escaleras.',flavor:'Recalculando tu coartada.',rarity:2,role:'utility',rule:{gps:1}},
  {id:'stained_map',name:'MAPA MANCHADO',description:'Revela una sala especial al comenzar cada piso.',flavor:'Esperemos que sea café.',rarity:2,role:'utility',rule:{stainedMap:1}},
  {id:'guard_glasses',name:'LENTES DEL GUARDIA',description:'Revela al jefe al despejar 60% de las salas normales.',flavor:'Ya se ve por dónde va el asunto.',rarity:2,role:'utility',rule:{guardLenses:1}},
  {id:'informant',name:'SOPLÓN',description:'Revela la tienda. Sus precios suben 5%.',flavor:'La información cuesta.',rarity:2,role:'utility',rule:{shopReveal:1,shop:.05}},
  {id:'ground_pepper',name:'PIMIENTA EN POLVO',description:'Los golpes críticos interrumpen ataques durante 0.4 s.',flavor:'Estornudar no es resistirse.',rarity:2,role:'defense',rule:{sneeze:24}},
  {id:'extra_butter',name:'MANTEQUILLA EXTRA',description:'Cada rebote aumenta el daño 20%, hasta +60%.',flavor:'Se les resbaló el presupuesto.',rarity:2,role:'offense',rule:{bounceDamage:.2}},
  {id:'steel_wings',name:'ALAS DE ACERO',description:'El esquive causa 12 de daño a los enemigos que atraviesas.',flavor:'Permiso. Con fuerza.',rarity:3,role:'offense',rule:{dashDamage:12}},
  {id:'burnt_bread',name:'PAN QUEMADO',description:'20% de prender fuego por 3 s con cada disparo.',flavor:'El panadero dice que es artesanal.',rarity:2,role:'offense',rule:{burnChance:.2}},
  {id:'sticky_honey',name:'MIEL PEGAJOSA',description:'Cada impacto reduce 4% la velocidad; máximo 45%.',flavor:'Ahora sí, no te muevas.',rarity:2,role:'defense',rule:{sticky:.04}},
  {id:'confetti_egg',name:'HUEVO CON CONFETI',description:'Una baja crítica explota y causa 12 de daño cercano.',flavor:'Sorpresa para todos.',rarity:3,role:'offense',rule:{confetti:12}},
  {id:'portable_alarm',name:'ALARMA PORTÁTIL',description:'+1 enemigo en salas normales. +12% recompensa.',flavor:'La discreción estaba sobrevalorada.',rarity:2,role:'utility',rule:{extraEnemy:1,rewardChance:.12}},
  {id:'bread_bag',name:'BOLSA DE PAN',description:'Cada 5 salas despejadas deja una comida.',flavor:'Todavía viene calientito.',rarity:2,role:'defense',rule:{foodEvery:5}},
  {id:'lucky_duck',name:'PATO DE LA SUERTE',description:'8% de sobrevivir un golpe mortal con media vida. Una vez.',flavor:'Hoy no, oficial.',rarity:3,role:'defense',rule:{lethalSave:.08}},
  {id:'double_barrel',name:'CAÑÓN DOBLE',description:'Duplica los proyectiles. Cada uno causa 70% del daño.',flavor:'Dos cañones, la misma mala idea.',rarity:3,role:'offense',rule:{twinCannon:1}},
  {id:'spiral_feathers',name:'PLUMAS EN ESPIRAL',description:'Tus disparos orbitan 0.5 s y salen en espiral.',flavor:'Dar vueltas también es una estrategia.',rarity:3,role:'offense',rule:{spiral:1}},
  {id:'infiltrator_chicken',name:'POLLO INFILTRADO',description:'Un pollo dispara 5 de daño a policías cada segundo.',flavor:'Cacarea muy bajito.',rarity:2,role:'offense',rule:{chicken:1}},
  {id:'bodyguard_duck',name:'PATO GUARDAESPALDAS',description:'Un pato bloquea un proyectil cada 12 s.',flavor:'Su contrato incluye pan.',rarity:2,role:'defense',rule:{bodyguard:1}},
  {id:'infinite_baguette',name:'BAGUETTE INFINITA',description:'Armas explosivas: +40% área; -20% cadencia de disparo.',flavor:'Más pan del que puedes manejar.',rarity:3,role:'offense',rule:{explosionScale:.4,explosiveRate:-.2}},
  {id:'radioactive_crumbs',name:'MIGAJAS RADIACTIVAS',description:'25% de dejar una zona dañina al derrotar enemigos.',flavor:'Brillan sin necesidad de lámpara.',rarity:3,role:'offense',rule:{radiation:.25}},
  {id:'forbidden_bread',name:'EL PAN PROHIBIDO',description:'+50% daño. -2 vida máxima.',flavor:'El ingrediente secreto era peligro.',rarity:4,role:'offense',rule:{damageScale:.5,maxHearts:-2}},
  {id:'crumb_crown',name:'CORONA DE MIGAJAS',description:'+5% daño por cada 25 migajas. Máximo +30%.',flavor:'El rey también cuenta el cambio.',rarity:4,role:'offense',rule:{crown:1}},
  {id:'stolen_watch',name:'RELOJ ROBADO',description:'Los tiempos de recarga avanzan 25% más rápido.',flavor:'Tiempo prestado. Sin permiso.',rarity:4,role:'utility',rule:{cooldownRate:.25}},
  {id:'bank_debt',name:'DEUDA BANCARIA',description:'+30% daño. Precios de la tienda +30%.',flavor:'Hasta el daño paga intereses.',rarity:3,role:'offense',rule:{damageScale:.3,shop:.3},cursed:true},
  {id:'wanted_duck',name:'PATO BUSCADO',description:'+20% velocidad. +12% enemigos élite desde el piso 2.',flavor:'Tu foto salió muy bien.',rarity:3,role:'utility',rule:{speed:.2,eliteChance:.12},cursed:true},
  {id:'expired_bread',name:'PAN CADUCADO',description:'+25% cadencia de disparo. La comida cura 25% menos.',flavor:'La fecha era una sugerencia.',rarity:3,role:'offense',rule:{fireRate:.25,healing:-.25},cursed:true},
  {id:'overdraft_card',name:'TARJETA SOBREGIRADA',description:'+40 migajas. Pagas 5 al entrar a salas, hasta devolver 40.',flavor:'El banco siempre cobra.',rarity:3,role:'utility',rule:{overdraft:40},cursed:true},
  {id:'fake_id',name:'CREDENCIAL FALSA',description:'El nivel de alerta aumenta 20% más lento.',flavor:'Sí, esa foto es tuya.',rarity:2,role:'utility',rule:{alertGrowth:-.2}},
];