const EN:Record<string,string>={
'Monedas':'Coins',
'COMPRADO':'PURCHASED',
'MIGAJAS INSUFICIENTES':'NOT ENOUGH CRUMBS',
'EL ATRACO FRACASÓ':'THE HEIST FAILED',
'EL PAN ES NUESTRO':'THE BREAD IS OURS',
'¡El pan pertenece a los patos!':'The bread belongs to the ducks!',
'Pan robado':'Bread stolen',
'Enemigos derrotados':'Enemies defeated',
'Salas despejadas':'Rooms cleared',
'Monedas obtenidas':'Coins earned',
'Pisos superados':'Floors cleared',
'REINTENTAR':'TRY AGAIN',
'JUGAR DE NUEVO':'PLAY AGAIN',
'MEJOR PARTIDA':'BEST RUN',
'PISO':'FLOOR',
'MANTÉN R PARA REINICIAR':'HOLD R TO RESTART',
'EXPEDIENTE DEL ÚLTIMO GOLPE':'FINAL HIT REPORT',
'DERROTADO POR':'KILLED BY',
'GOLPE FINAL':'FINAL BLOW',
'ENEMIGO':'ENEMY',
'PELIGRO':'HAZARD',
'SEGURIDAD DEL BANCO':'BANK SECURITY',
'EMBESTIDA DEL JEFE':'BOSS CHARGE',
'GOLPE DE PORRA':'BATON STRIKE',
'EMBESTIDA CON ESCUDO':'SHIELD CHARGE',
'EMBESTIDA DEL GANSO':'GOOSE CHARGE',
'ATROPELLO RODANTE':'ROLLING IMPACT',
'ATAQUE CUERPO A CUERPO':'MELEE ATTACK',
'DISPARO DE FRANCOTIRADOR':'SNIPER SHOT',
'RÁFAGA DE ESCOPETA':'SHOTGUN BLAST',
'MONEDA BALÍSTICA':'BALLISTIC COIN',
'BOMBA DE MASA':'DOUGH BOMB',
'TOSTADA BALÍSTICA':'BALLISTIC TOAST',
'MALETÍN PROYECTIL':'FLYING BRIEFCASE',
'PROYECTIL DE SEGURIDAD':'SECURITY PROJECTILE',
'DISPARO DEL JEFE':'BOSS SHOT',
'DISPARO':'GUNSHOT',
'PROYECTIL ENEMIGO':'ENEMY PROJECTILE',
'CAUSA DESCONOCIDA':'UNKNOWN CAUSE',
'CONSEJO: ROMPE LA LÍNEA DE TIRO CUANDO APAREZCA LA MIRA.':'TIP: BREAK LINE OF SIGHT WHEN THE SCOPE APPEARS.',
'CONSEJO: MANTÉN DISTANCIA Y ESQUIVA DESPUÉS DEL TELÉGRAFO.':'TIP: KEEP YOUR DISTANCE AND DASH AFTER THE TELEGRAPH.',
'CONSEJO: RODÉALO; SUS COSTADOS Y ESPALDA SON VULNERABLES.':'TIP: FLANK IT; ITS SIDES AND BACK ARE VULNERABLE.',
'CONSEJO: DEJA UNA RUTA DE ESCAPE Y NO TE QUEDES CONTRA LA PARED.':'TIP: KEEP AN ESCAPE ROUTE AND STAY OFF THE WALLS.',
'CONSEJO: LEE EL TELÉGRAFO; CADA FASE DEJA UNA VENTANA PARA CASTIGAR.':'TIP: READ THE TELEGRAPH; EVERY PHASE LEAVES A PUNISH WINDOW.',
'CONSEJO: GUARDA EL ESQUIVE PARA EL ÚLTIMO INSTANTE DEL PROYECTIL.':'TIP: SAVE YOUR DASH FOR THE PROJECTILE’S LAST MOMENT.',
'EL BANCO COBRÓ LA ÚLTIMA COMISIÓN.':'THE BANK CHARGED ONE LAST FEE.',
'EL MINIJEFE CERRÓ TU CUENTA.':'THE MINIBOSS CLOSED YOUR ACCOUNT.',
'UN ÉLITE TE CERRÓ LA CAJA.':'AN ELITE CLOSED THE REGISTER ON YOU.',
'NUNCA VISTE VENIR LA FACTURA.':'YOU NEVER SAW THE BILL COMING.',
'DEMASIADO CERCA. DEMASIADAS MIGAJAS.':'TOO CLOSE. TOO MANY CRUMBS.',
'EL ATRACO TERMINÓ, PERO EL PAN SIGUE AHÍ.':'THE HEIST IS OVER, BUT THE BREAD IS STILL THERE.',
'MONEDAS GUARDADAS':'COINS BANKED',
'TOTAL':'TOTAL',
'¡PUERTAS BLOQUEADAS!':'DOORS LOCKED!',
'PUERTAS ABIERTAS':'DOORS OPEN',
'ALERTA':'ALERT',
'Comprar':'Buy',
'RECOGER':'PICK UP',
'Abrir':'Open',
'Migajas':'Crumbs',
'VENDIDO':'SOLD',
'TIENDA CLANDESTINA':'BLACK MARKET',
'DON MIGAJÓN':'DON CRUMB',
'Acércate para recoger el objeto':'Move closer to pick up the item',
'¡NUEVO OBJETO!':'NEW ITEM!',
'¡NUEVA ARMA!':'NEW WEAPON!',
'BLOQUEO':'BLOCK',
'ENTRADA DEL BANCO':'BANK ENTRANCE',
'OFICINAS DE SEGURIDAD':'SECURITY OFFICES',
'ALMACÉN DE PAN':'BREAD STORAGE',
'PANADERÍA SUBTERRÁNEA':'UNDERGROUND BAKERY',
'BÓVEDA DE ALTA SEGURIDAD':'HIGH-SECURITY VAULT',
'LA CÁMARA DEL PAN DORADO':'GOLDEN BREAD CHAMBER',
'SALA DE OBJETOS':'ITEM ROOM',
'SALA DEL TESORO':'TREASURE ROOM',
'TIENDA':'SHOP',
'MINIJEFE':'MINIBOSS',
'JEFE':'BOSS',
'BÓVEDA SECRETA':'SECRET VAULT',
'SALA NORMAL':'NORMAL ROOM',
'SALA ESPECIAL':'SPECIAL ROOM',
'DESAFÍO':'CHALLENGE',
'SALA SECRETA':'SECRET ROOM',
'RECOMPENSA':'REWARD',
'CUAC-BLÁSTER':'QUACK BLASTER',
'Dispara ondas sónicas de cuac':'Fires sonic quack waves',
'Cada sexto disparo es un CUAC POTENTE: más daño y empujón.':'Every sixth shot is a POWER QUACK: more damage and knockback.',
'ESCOPETA DE MIGAS':'CRUMB SHOTGUN',
'Perdigones de pan en abanico':'A spread of bread pellets',
'AMETRALLADORA DE PLUMAS':'FEATHER MACHINE GUN',
'Plumas rapidísimas, poco daño':'Very fast feathers, low damage',
'BUMERÁN DE PAN':'BREAD BOOMERANG',
'CAÑÓN DE PATITOS':'RUBBER DUCK CANNON',
'Cada rebote suma 10% de daño. Rechina en las paredes.':'Each bounce adds 10% damage. It squeaks off the walls.',
'LANZA-BAGUETTES':'BAGUETTE LAUNCHER',
'Baguettes explosivas de área':'Explosive area-damage baguettes',
'Impacto directo: +25% daño. Explota en área.':'Direct hit: +25% damage. Explodes in an area.',
'LÁSER CUAC':'QUACK LASER',
'Rayo sónico continuo':'Continuous sonic beam',
'Atraviesa todo. El daño sube si mantienes la mira.':'Pierces everything. Damage ramps while you hold aim.',
'REVÓLVER DE HUEVO DORADO':'GOLDEN EGG REVOLVER',
'Mucho daño, lento, críticos':'High damage, slow, critical hits',
'Mantén la mira: el siguiente tiro gana crítico dorado.':'Hold aim: the next shot gains a golden critical.',
'TOSTADORA TÁCTICA':'TACTICAL TOASTER',
'Tres tostadas en un enemigo: explosión.':'Three toast stacks on an enemy: explosion.',
'CAÑÓN DE HUEVOS':'EGG CANNON',
'Mantén para apuntar. Suelta para un disparo rápido.':'Hold to aim. Release for a quick shot.',
'FRANCOTIRADOR BAGUETTE':'BAGUETTE SNIPER',
'Perfora varios enemigos. Alta precisión.':'Pierces several enemies. High accuracy.',
'PANADERA DE PLASMA':'PLASMA BAKERY',
'Mantén para cargar un pan de plasma.':'Hold to charge a plasma loaf.',
'Toque: disparo chico. Carga máxima: perfora.':'Tap: small shot. Full charge: pierces.',
'PISTOLA DE MIGAS RASTREADORAS':'HOMING CRUMB PISTOL',
'Daño bajo. Ayuda a aprender a apuntar.':'Low damage. Helps you learn to aim.',
'CASCO DE PAN':'BREAD HELMET',
'+1 de vida y menos daño al chocar':'+1 health and less collision damage',
'PATA DE CONEJO ROBADA':'STOLEN RABBIT FOOT',
'Más críticos y mejores botines':'More critical hits and better loot',
'CALCETINES CON MANTEQUILLA':'BUTTER SOCKS',
'Te mueves más rápido y resbalas':'Move faster and slide around',
'MAMÁ PATA':'MOTHER DUCK',
'IMÁN DE PAN':'BREAD MAGNET',
'Los enemigos sueltan más migas':'Enemies drop more crumbs',
'PLUMA DE GANSO FURIOSO':'ANGRY GOOSE FEATHER',
'+30% daño, enemigos más rápidos':'+30% damage, enemies move faster',
'BANDEJA DE METAL':'METAL TRAY',
'20% de bloquear el daño':'20% chance to block damage',
'SILENCIADOR DE CUAC':'QUACK SILENCER',
'La policía tarda más en disparar':'Police take longer to shoot',
'PLANO DE LA BÓVEDA':'VAULT BLUEPRINT',
'Revela todo el mapa del piso':'Reveals the entire floor map',
'CINTURÓN ANCHO':'WIDE BELT',
'Más migajas por enemigo y esquive más frecuente':'More crumbs per enemy and more frequent dashes',
'CUAC DE EMERGENCIA':'EMERGENCY QUACK',
'BOMBA DE PAN':'BREAD BOMB',
'SEÑUELO DE PATO':'RUBBER DUCK DECOY',
'POLICÍA FRANCOTIRADOR':'POLICE SNIPER',
'POLICÍA MÉDICO':'POLICE MEDIC',
'CAPITÁN DE PATRULLA':'PATROL CAPTAIN',
'UNIDAD K9: GANSO':'K9 UNIT: GOOSE',
'CÁMARA DE SEGURIDAD':'SECURITY CAMERA',
'POLICÍA PATO':'DUCK POLICE',
'POLICÍA RÁPIDO':'FAST COP',
};
export default EN;