const EN:Record<string,string>={
'POLICÍA ESCOPETA':'SHOTGUN COP',
'POLICÍA ANTIDISTURBIOS':'RIOT COP',
'PALOMA DE SEGURIDAD':'SECURITY PIGEON',
'GANSO GUARDIA':'GUARD GOOSE',
'POLICÍA GRANADERO':'GRENADIER COP',
'POLICÍA CON PORRA':'BATON COP',
'CÁMARA MÓVIL':'MOBILE CAMERA',
'Dispara más preciso y rápido':'Shoots faster and more accurately',
'Dos ráfagas seguidas':'Two bursts in a row',
'Escudo más grande y embestidas dobles':'Bigger shield and double charges',
'Ráfagas en abanico':'Fan-shaped bursts',
'Carga más larga':'Longer charge',
'Lanza más monedas':'Throws more coins',
'La mira se traba más rápido':'Locks aim faster',
'CAPITÁN HONK':'CAPTAIN HONK',
'Jefe de seguridad del banco':'Head of bank security',
'Ordena formaciones y cubre el vestíbulo':'Commands formations and covers the lobby',
'COMISARIO PICO DURO':'COMMISSIONER HARD-BEAK',
'LA TOSTADORA 9000':'TOASTER 9000',
'Electrodoméstico poseído':'Possessed appliance',
'GENERAL GANSO':'GENERAL GOOSE',
'Armadura de ganso. Después corre más':'Goose armor. Then it runs faster',
'DON LEVADURA':'DON YEAST',
'Masa mutante de la panadería':'Mutant bakery dough',
'DIRECTOR DE SEGURIDAD':'SECURITY DIRECTOR',
'Láseres, drones y barreras':'Lasers, drones, and barriers',
'EL BANQUERO DEL PAN':'THE BREAD BANKER',
'Amo y señor de todo el pan':'Master and lord of all bread',
'EL RECAUDADOR':'THE COLLECTOR',
'Un ganso furioso con traje':'An angry goose in a suit',
'EL PANADERO JEFE':'HEAD BAKER',
'SARGENTO MIGAJAS':'THE CRUMB SERGEANT',
'EL AUDITOR':'THE AUDITOR',
'GANSO ANTIDISTURBIOS':'RIOT GOOSE',
'DRON CENTINELA':'SENTRY DRONE',
'EL PANADERO LOCO':'THE MAD BAKER',
'CAJERO 3000':'TELLER 3000',
'Monedas, láser y botín extra':'Coins, lasers, and extra loot',
'PATO LADRÓN':'HEIST DUCK',
'PATO GÁNSTER':'GANGSTER DUCK',
'PATO PRESIDIARIO':'PRISON DUCK',
'PATO PANADERO':'BAKER DUCK',
'PATO EJECUTIVO':'EXECUTIVE DUCK',
'Traje oscuro, corbata y maletín.':'Dark suit, tie, and briefcase.',
'PATO ROSA':'PINK DUCK',
'PATO NINJA':'NINJA DUCK',
'PATO POLICÍA INFILTRADO':'UNDERCOVER POLICE DUCK',
'Absolutamente nadie sospechará.':'Absolutely nobody will suspect a thing.',
'PATO PIRATA':'PIRATE DUCK',
'Busca el pan enterrado.':'Searching for buried bread.',
'PATO DORADO':'GOLDEN DUCK',
'El crimen nunca había brillado tanto.':'Crime has never shined this bright.',
'PATO REY DEL PAN':'BREAD KING DUCK',
'El clásico. Amarillo, sospechoso y sorprendentemente profesional.':'The classic. Yellow, suspicious, and surprisingly professional.',
'PANADERÍA PROPIA':'PRIVATE BAKERY',
'+1 corazón de vida inicial':'+1 starting heart',
'+10% de daño':'+10% damage',
'Esquive más frecuente':'More frequent dash',
'Cuantos más cuacs, mejor.':'The more quacks, the better.',
'Un poco de pluma nunca lastimó... mentira.':'A little feather never hurt anyone... lie.',
'Ingeniería militar aplicada correctamente.':'Military engineering applied correctly.',
'Un arma de destrucción y de desayuno.':'A weapon of destruction and breakfast.',
'Un cuac continuo viola varias normas bancarias.':'A continuous quack violates several banking regulations.',
'Le robó la suerte a alguien.':'Stole somebody else’s luck.',
'Más rápido que el gerente en quiebra.':'Faster than a bankrupt manager.',
'Nadie se mete con su cría.':'Nobody messes with her duckling.',
'Alguien está de muy mal humor.':'Someone is in a very bad mood.',
'Lo duro también sirve.':'Hard things work too.',
'La corrupción tiene agujero.':'Corruption has a hole in it.',
'Sacado de un cajón sin candado.':'Taken from an unlocked drawer.',
'Espacio para más botín.':'Room for more loot.',
'Un cuac que se escucha hasta en la cárcel.':'A quack you can hear all the way from jail.',
'Un compañero de goma muy leal.':'A very loyal rubber accomplice.',
'MIGAS MAGNÉTICAS':'MAGNETIC CRUMBS',
'Las migas vuelan hacia ti desde mucho más lejos':'Crumbs fly toward you from much farther away',
'+15% velocidad de movimiento y esquive más largo':'+15% move speed and longer dash',
'Seguridad recomendó el letrero de piso mojado.':'Security recommended the wet-floor sign.',
'PAN DE AJO':'GARLIC BREAD',
'Los enemigos cercanos reciben daño cada segundo':'Nearby enemies take damage every second',
'Excelente contra policías y citas románticas.':'Great against police and romantic dates.',
'CAFÉ DE GASOLINERA':'GAS-STATION COFFEE',
'+20% de cadencia, -5% de precisión':'+20% fire rate, -5% accuracy',
'MAYONESA TÁCTICA':'TACTICAL MAYONNAISE',
'Los enemigos que golpeas se mueven un 15% más lento':'Enemies you hit move 15% slower',
'Aderezo de uso táctico.':'Tactical-grade dressing.',
'CÁSCARA DE HUEVO':'EGGSHELL',
'Escudo que absorbe 1 golpe al entrar en cada piso':'Shield that absorbs 1 hit when entering each floor',
'Frágil, pero un golpe te salva.':'Fragile, but one hit can save you.',
'+1% de daño por cada 10 migas (máximo +30%)':'+1% damage per 10 crumbs (max +30%)',
'El interés compuesto es un arma.':'Compound interest is a weapon.',
'CHALECO DE CARTÓN':'CARDBOARD VEST',
'Pasó dos de tres pruebas.':'Passed two out of three tests.',
'MAPA ROBADO':'STOLEN MAP',
'Revela una sala vecina más en el minimapa':'Reveals one extra neighboring room on the minimap',
'Un callejón menos por explorar.':'One less hallway to explore.',
'MONÓCULO SOSPECHOSO':'SUSPICIOUS MONOCLE',
'Aparecen más objetos raros en el botín':'More rare items appear in loot',
'ALARMA ROTA':'BROKEN ALARM',
'Nadie oirá tus triunfos.':'Nobody will hear your victories.',
'ALARMA FALSA':'FALSE ALARM',
'Pánico enlatado.':'Canned panic.',
'Dobla tu cadencia de disparo durante 6 segundos':'Doubles your fire rate for 6 seconds',
'Cafeína industrial de contrabando.':'Smuggled industrial caffeine.',
'MEGÁFONO CUAC':'QUACK MEGAPHONE',
'Onda cuac que daña y empuja a todos los enemigos':'Quack wave that damages and pushes every enemy',
'CUAC. En mayúsculas.':'QUACK. In all caps.',
};
export default EN;