import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {ROWS,IDS} from './arsenal47Data.mjs';
const once=(s,re,to,label)=>{const n=s.replace(re,to);if(n===s)throw new Error('Arsenal47 patch failed: '+label);return n;};
const EXTRA=`
const EXTRA_WEAPON_ROWS:any[][]=${JSON.stringify(ROWS)};
for(const r of EXTRA_WEAPON_ROWS){const [id,name,description,special,fireRate,damage,projectileSpeed,projectileType,spread,projectileCount,knockback,piercing,bounces,continuous,boomerang,explode,cost,rarity,dmg,rate,range,speed]=r;WEAPONS[id]={id,name,description,special,fireRate,damage,projectileSpeed,projectileType,spread,projectileCount,knockback,piercing,bounces,continuous,boomerang,...(explode?{explode}:{}),cost,rarity,bars:{dmg,rate,range,speed}};}
`;
export function applyDuckArsenalContent(gameDir){
 const data=path.join(gameDir,'game','data.ts');let d=readFileSync(data,'utf8');
 d=once(d,/  receipt_ripper: \{[\s\S]*?\n  \},\n\};/,m=>m+EXTRA,'weapon rows');
 d=once(d,/  \| 'ninja' \| 'undercover' \| 'pirate' \| 'gold' \| 'king';/,"  | 'ninja' | 'undercover' | 'pirate' | 'gold' | 'king' | 'space_green';",'skin type');
 d=once(d,/\];\n\nexport function getSkin/,`];\nSKINS.push({id:'jalo_verde',name:'JALO VERDE',description:'Armadura espacial verde, visor ámbar y cero preguntas sobre la misión.',cost:450,palette:{...DEFAULT_PALETTE,body:'#66783d',dark:'#42502d',shade:'#2d3923',beak:'#d89a34',beakDark:'#a76b20',mask:'#151b19',pack:'#283126',strap:'#1d241d'},overlay:'space_green'});\n\nexport function getSkin`,'Jalo skin');writeFileSync(data,d);
 const stf=path.join(gameDir,'game','selftest.ts');let st=readFileSync(stf,'utf8');st=st.replace("check('Exactly eleven cosmetic skins',()=>assert(SKINS.length===11","check('Exactly twelve cosmetic skins',()=>assert(SKINS.length===12");st=once(st,/    check\('Exactly twelve cosmetic skins',[^\n]+\n/,m=>m+"    check('Exactly forty-seven weapons',()=>assert(Object.keys(WEAPONS).length===47,'weapon count'));\n",'count test');writeFileSync(stf,st);
 const art=path.join(gameDir,'game','itemArt.ts');let ia=readFileSync(art,'utf8');const ids=JSON.stringify(IDS);ia=once(ia,/const mystery: IconPainter = p => \{/,`const ARSENAL_WEAPON_IDS=new Set<string>(${ids});\nconst arsenalIcon=(id:string):IconPainter=>p=>{let h=2166136261;for(const c of id){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}const cs=[C.gold,C.blue,C.green,C.red,C.purple,C.orange,C.silver],a=cs[Math.abs(h)%cs.length],b=cs[Math.abs(h>>4)%cs.length],n=13+(Math.abs(h>>8)%7),y=8+(Math.abs(h>>12)%5);p.rect(3,y,n,5,a);p.rect(6,y+5,5,7,C.dark);p.rect(n,y+1,Math.max(3,21-n),3,C.silver);p.line(5,y+1,Math.min(18,n+2),y+1,b);if(h&1)p.oval(10,y+2,3,3,C.light);if(h&2)p.poly([[n-2,y-2],[22,y+2],[n-2,y+6]],b);if(h&4)p.rect(8,y-3,7,2,C.steel);};\nconst mystery: IconPainter = p => {`,'weapon icons');ia=once(ia,/export function getIconPixels\(id: string\) \{\n  const p = new PixelPainter\(\);\n  \(ITEM_ART\[id\] \?\? mystery\)\(p\);/,`export function getIconPixels(id:string){\n  const p=new PixelPainter();const painter=ITEM_ART[id]??(ARSENAL_WEAPON_IDS.has(id)?arsenalIcon(id):mystery);painter(p);`,'icon resolver');writeFileSync(art,ia);
 const sprites=path.join(gameDir,'game','sprites.ts');let sp=readFileSync(sprites,'utf8');sp=once(sp,/    default: \{\n      ctx\.fillStyle = '#fff';\n      ctx\.beginPath\(\);\n      ctx\.arc\(bx, by, 3, 0, Math\.PI \* 2\);\n      ctx\.fill\(\);\n    \}/,`    default:{let h=0;for(let i=0;i<type.length;i++)h=(h*31+type.charCodeAt(i))|0;const cs=['#f4d03f','#61c7dd','#9ad27d','#e87068','#b58bdd','#f0a45b','#d8e0e8'];ctx.fillStyle=cs[Math.abs(h)%cs.length];if(type==='black_crumb'){ctx.fillStyle='rgba(120,78,170,.25)';ctx.beginPath();ctx.arc(bx,by,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#08090d';ctx.beginPath();ctx.arc(bx,by,4,0,Math.PI*2);ctx.fill();}else if(type==='vault_magnet_orb'){ctx.globalAlpha=.32;ctx.beginPath();ctx.arc(bx,by,8,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;rect(ctx,bx-3,by-3,2,6,'#e8574f');rect(ctx,bx+1,by-3,2,6,'#4b9db5');}else if(type==='orbit_duck'){rect(ctx,bx-3,by-1,6,4,'#ffd95e');rect(ctx,bx+2,by,3,2,'#f0912b');px(ctx,bx,by-1,'#15151f',1);}else if((Math.abs(h)>>3)%2)rect(ctx,bx-4,by-1,8,3,ctx.fillStyle as string);else{ctx.beginPath();ctx.arc(bx,by,3+(Math.abs(h)%2),0,Math.PI*2);ctx.fill();}}`,'projectiles');sp=once(sp,/    default: break;\n  \}\n  ctx\.restore\(\);/i,`    case 'space_green':rect(ctx,bx+2,by-2,12,4,'#34432b');rect(ctx,bx+3,by-5,10,4,'#66783d');rect(ctx,bx+5,by-2,8,3,'#d69a3a');rect(ctx,bx+6,by-1,6,1,'#ffd86a');rect(ctx,bx+2,by+6,12,9,'#536638');rect(ctx,bx+4,by+8,8,5,'#2d3923');rect(ctx,bx+6,by+9,4,3,'#7f914a');rect(ctx,bx+1,by+7,3,6,'#42502d');rect(ctx,bx+12,by+7,3,6,'#42502d');rect(ctx,bx+7,by+11,2,2,'#f4d03f');break;\n    default: break;\n  }\n  ctx.restore();`,'Jalo art');writeFileSync(sprites,sp);
}
