import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
const once=(s,re,to,label)=>{const n=s.replace(re,to);if(n===s)throw new Error('Fair/balance/van patch failed: '+label);return n;};
const VAN_DRAW=`function drawBlackMarketVan(ctx:CanvasRenderingContext2D,f:number){
  const x=240,y=122;ctx.save();
  ctx.fillStyle='rgba(0,0,0,.32)';ctx.beginPath();ctx.ellipse(x,y+38,83,13,0,0,Math.PI*2);ctx.fill();
  ctx.fillStyle='#080b0f';ctx.fillRect(x-70,y-24,140,52);ctx.fillStyle='#141a20';ctx.fillRect(x-58,y-34,82,12);ctx.fillRect(x+24,y-28,36,56);
  ctx.fillStyle='#27333b';ctx.fillRect(x-48,y-29,28,15);ctx.fillRect(x-16,y-29,29,15);ctx.fillStyle='#5f8c98';ctx.globalAlpha=.38;ctx.fillRect(x-45,y-27,22,10);ctx.fillRect(x-13,y-27,23,10);ctx.globalAlpha=1;
  ctx.fillStyle='#020304';ctx.fillRect(x-64,y-18,79,39);ctx.fillStyle='#25190d';ctx.fillRect(x-48,y-14,58,31);ctx.fillStyle='#f0a34d';ctx.globalAlpha=.14+.05*Math.sin(f*.07);ctx.fillRect(x-46,y-12,54,27);ctx.globalAlpha=1;
  ctx.fillStyle='#242a2d';for(let i=0;i<3;i++){ctx.fillRect(x-42+i*17,y-7,13,3);ctx.fillRect(x-39+i*17,y-11,7,2);}ctx.fillStyle='#e79a45';ctx.fillRect(x-48,y+18,58,2);
  ctx.fillStyle='#11161b';ctx.fillRect(x+31,y-14,29,29);ctx.fillStyle='#6f7c80';ctx.fillRect(x+34,y-10,23,2);ctx.fillRect(x+34,y-3,23,2);ctx.fillRect(x+34,y+4,23,2);
  for(const wx of [x-45,x+45]){ctx.fillStyle='#050608';ctx.beginPath();ctx.arc(wx,y+29,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#394149';ctx.beginPath();ctx.arc(wx,y+29,6,0,Math.PI*2);ctx.fill();}
  ctx.fillStyle='#f2b45d';ctx.fillRect(x+65,y-8,4,7);ctx.fillStyle='#c83f35';ctx.fillRect(x-70,y-8,3,8);
  ctx.fillStyle='#d8913d';ctx.fillRect(x+37,y+17,14,3);ctx.fillStyle='#090b0e';ctx.fillRect(x+40,y+18,8,1);
  drawShopPigeon(ctx,x+80,y+5,f);ctx.restore();
}`;
export function applyDuckFairBalanceVan(gameDir){
  const constants=path.join(gameDir,'game','constants.ts');let c=readFileSync(constants,'utf8');
  c=once(c,/  SHOP = 'SHOP',\n/,"  SHOP = 'SHOP',\n  GUN_VAN = 'GUN_VAN',\n",'room type');writeFileSync(constants,c);
  const mapgen=path.join(gameDir,'game','mapgen.ts');let m=readFileSync(mapgen,'utf8');
  m=once(m,/  assignMiddle\(remaining\(\), RoomType\.SHOP\);\n/,"  assignMiddle(remaining(), RoomType.SHOP);\n  if(remaining().length>7&&random()<.42)assignDeadEndOrRandom(remaining(),RoomType.GUN_VAN,random);\n",'van generation');
  m=once(m,/  if \(room\.type === RoomType\.ITEM \|\| room\.type === RoomType\.SHOP \|\|\n      room\.type === RoomType\.BOSS/,"  if (room.type === RoomType.ITEM || room.type === RoomType.SHOP || room.type === RoomType.GUN_VAN ||\n      room.type === RoomType.BOSS",'van clear layout');writeFileSync(mapgen,m);
  const data=path.join(gameDir,'game','data.ts');let d=readFileSync(data,'utf8');
  d=once(d,/\nexport interface ItemDef \{/,`\n// Balance 2.0: el Cuac-Bláster es fiable, no el mejor DPS del arsenal.\nWEAPONS.quack_blaster.fireRate=18;WEAPONS.quack_blaster.damage=7;WEAPONS.quack_blaster.knockback=1.4;WEAPONS.quack_blaster.bars={dmg:2,rate:2,range:3,speed:3};\nfor(const [id,w] of Object.entries(WEAPONS)){if(id==='quack_blaster')continue;const boost=1.02+Math.min(4,w.rarity)*.025;w.damage=Math.round(w.damage*boost*10)/10;}\n\nexport interface ItemDef {`,'weapon rebalance');d=d.replace("description:'Armadura espacial verde, visor ámbar y cero preguntas sobre la misión.'","description:'Armadura verde de asalto espacial, casco reforzado y visor dorado.'");writeFileSync(data,d);
  const engine=path.join(gameDir,'game','engine.ts');let e=readFileSync(engine,'utf8');
  e=once(e,/  const spots = freeTiles\(room\.layout, 2\);/,`  const spots=freeTiles(room.layout,2).filter(s=>room.doors.every(dir=>{const dt=DOOR_TILE[dir];return Math.hypot(s.x-dt.x,s.y-dt.y)>=3.5;}));`,'safe spawn tiles');
  e=once(e,/    case RoomType\.SHOP: \{[\s\S]*?      content\.shopItems = shop;\n      break;\n    \}/,`    case RoomType.SHOP:{\n      const first=pickPassive(engine)??fallbackActive(engine);const second=pickPassive(engine,undefined,[first])??fallbackActive(engine);const third=pickPassive(engine,undefined,[first,second])??fallbackActive(engine);\n      const itemPool=[first,second,third].filter(Boolean) as string[];content.shopItems=itemPool.map((id,i)=>({itemId:id,cost:(ITEMS[id]??ACTIVE_ITEMS[id]).cost,sold:false,isWeapon:false,x:CANVAS_WIDTH*(.28+i*.22),y:CANVAS_HEIGHT*.58}));break;\n    }\n    case RoomType.GUN_VAN:{\n      const owned=new Set(engine.player.weapons.filter(Boolean).map(w=>w!.id));let pool=Object.keys(WEAPONS).filter(id=>id!=='quack_blaster'&&!owned.has(id));if(pool.length<3)pool=Object.keys(WEAPONS).filter(id=>id!=='quack_blaster');const offers:string[]=[];while(offers.length<3&&pool.length){const i=Math.floor(Math.random()*pool.length);offers.push(pool.splice(i,1)[0]);}\n      content.shopItems=offers.map((id,i)=>({itemId:id,cost:Math.max(8,WEAPONS[id].cost),sold:false,isWeapon:true,x:145+i*95,y:235}));break;\n    }`,'shop and gun van');
  e=once(e,/  engine\.player\.vx = 0; engine\.player\.vy = 0;/,"  engine.player.vx=0;engine.player.vy=0;if(from)engine.player.iFrames=Math.max(engine.player.iFrames,50);",'entry grace');
  e=once(e,/if\(from\) playDoorStyle\(room\.type===RoomType\.BOSS\?'boss':room\.type===RoomType\.ITEM\?'gold':room\.type===RoomType\.SHOP\?'green':room\.type===RoomType\.TREASURE\?'purple':'silver'\);/,"if(from)playDoorStyle(room.type===RoomType.BOSS?'boss':room.type===RoomType.ITEM?'gold':room.type===RoomType.SHOP?'green':room.type===RoomType.GUN_VAN?'orange':room.type===RoomType.TREASURE?'purple':'silver');",'van door sound');
  e=once(e,/  if\(room\.type===RoomType\.SHOP && \(content\.merchantUntil \?\? 0\)<engine\.frame\) merchantSpeak\(engine,pick\(\['Todo legal\. Probablemente\.','No tengo factura\.','Eso cayó de un camión\.','El pan está caro\.','No hago devoluciones\.','Ese objeto no estaba aquí ayer\.'\]\)\);/,`  if((room.type===RoomType.SHOP||room.type===RoomType.GUN_VAN)&&(content.merchantUntil??0)<engine.frame)merchantSpeak(engine,room.type===RoomType.GUN_VAN?pick(['Tres fierros. Cero preguntas.','La camioneta no existe.','Mira rápido y paga en migajas.','No preguntes de dónde salieron.']):pick(['Todo legal. Probablemente.','No tengo factura.','Eso cayó de un camión.','El pan está caro.','No hago devoluciones.','Ese objeto no estaba aquí ayer.']));`,'van merchant lines');
  e=once(e,/    case RoomType\.SHOP: return 'TIENDA CLANDESTINA';/,"    case RoomType.SHOP:return 'TIENDA CLANDESTINA';\n    case RoomType.GUN_VAN:return 'CAMIONETA DEL MERCADO NEGRO';",'van room label');
  e=once(e,/if\(powerQuack\)\{dmg\*=1\.6;type='quack_power';projRadius=Math\.max\(projRadius,4\);\}/,"if(powerQuack){dmg*=1.4;type='quack_power';projRadius=Math.max(projRadius,4);}",'starter power shot');writeFileSync(engine,e);
  const floor=path.join(gameDir,'game','floorMap.ts');let fm=readFileSync(floor,'utf8');
  fm=once(fm,/  \[RoomType\.SHOP\]:\{label:'TIENDA',color:'#71c799',symbol:'shop'\},/,"  [RoomType.SHOP]:{label:'TIENDA',color:'#71c799',symbol:'shop'},\n  [RoomType.GUN_VAN]:{label:'CAMIONETA',color:'#e79a45',symbol:'van'},",'map style');
  fm=once(fm,/return type==='shop'\?r\.type===RoomType\.SHOP:type==='boss'/,"return type==='shop'?(r.type===RoomType.SHOP||r.type===RoomType.GUN_VAN):type==='boss'",'gps van');
  fm=once(fm,/if\(b\.shopReveal\) for\(const \[id,r\]of rooms\) if\(r\.type===RoomType\.SHOP\) reveal\(id\);/,"if(b.shopReveal)for(const [id,r]of rooms)if(r.type===RoomType.SHOP||r.type===RoomType.GUN_VAN)reveal(id);",'reveal van');
  fm=once(fm,/    case 'shop':rect\(2,2,8,2\);rect\(2,3,2,3\);rect\(3,5,7,2\);rect\(8,6,2,3\);rect\(2,9,8,2\);rect\(5,0,2,12\);break;/,`    case 'shop':rect(2,2,8,2);rect(2,3,2,3);rect(3,5,7,2);rect(8,6,2,3);rect(2,9,8,2);rect(5,0,2,12);break;\n    case 'van':rect(1,4,10,5);rect(3,2,5,3);c.fillStyle='#111820';rect(4,3,3,2);c.fillStyle=style.color;rect(2,9,2,2);rect(8,9,2,2);break;`,'van map glyph');writeFileSync(floor,fm);
  const i18n=path.join(gameDir,'game','i18n.ts');let il=readFileSync(i18n,'utf8');
  il=once(il,/  \[RoomType\.SHOP\]: 'TIENDA CLANDESTINA',/,"  [RoomType.SHOP]:'TIENDA CLANDESTINA',\n  [RoomType.GUN_VAN]:'CAMIONETA DEL MERCADO NEGRO',",'room localization');writeFileSync(i18n,il);
  const render=path.join(gameDir,'game','render.ts');let r=readFileSync(render,'utf8');
  r=once(r,/export function renderWorld\(engine: GameEngine\) \{/,VAN_DRAW+'\n\nexport function renderWorld(engine: GameEngine) {','van draw helper');
  r=once(r,/target\?\.type === RoomType\.BOSS \? 'boss' : target\?\.type===RoomType\.SHOP\?'green'/,"target?.type===RoomType.BOSS?'boss':target?.type===RoomType.SHOP?'green':target?.type===RoomType.GUN_VAN?'orange'",'van door visual');
  r=once(r,/  if \(room\.type === RoomType\.SHOP && content\.shopItems\) \{\n    drawShopPigeon\(ctx, CANVAS_WIDTH \/ 2 - 8, CANVAS_HEIGHT \* 0\.22, f\);\n    for \(const it of content\.shopItems\) \{/,`  if((room.type===RoomType.SHOP||room.type===RoomType.GUN_VAN)&&content.shopItems){\n    if(room.type===RoomType.GUN_VAN)drawBlackMarketVan(ctx,f);else drawShopPigeon(ctx,CANVAS_WIDTH/2-8,CANVAS_HEIGHT*.22,f);\n    for(const it of content.shopItems){`,'van world vendor');
  r=once(r,/  \} else if \(room\.type === RoomType\.SHOP\) \{\n    ctx\.fillStyle = 'rgba\(120,72,30,0\.28\)';/,`  } else if(room.type===RoomType.GUN_VAN){\n    ctx.fillStyle='rgba(3,5,8,.38)';ctx.fillRect(TILE_SIZE,TILE_SIZE,CANVAS_WIDTH-TILE_SIZE*2,CANVAS_HEIGHT-TILE_SIZE*2);ctx.fillStyle='rgba(231,154,69,.12)';for(let x=90;x<410;x+=70)ctx.fillRect(x,286,34,3);\n  } else if (room.type === RoomType.SHOP) {\n    ctx.fillStyle = 'rgba(120,72,30,0.28)';`,'van ambience');
  r=once(r,/    text\(ctx, 'DON MIGAJÓN', CANVAS_WIDTH \/ 2, CANVAS_HEIGHT \* 0\.16, 11, '#f4d03f', 'center', true\);/,"    text(ctx,room.type===RoomType.GUN_VAN?'EL PROVEEDOR':'DON MIGAJÓN',CANVAS_WIDTH/2,CANVAS_HEIGHT*.16,11,room.type===RoomType.GUN_VAN?'#e79a45':'#f4d03f','center',true);",'van prompt heading');writeFileSync(render,r);
  const sprites=path.join(gameDir,'game','sprites.ts');let sp=readFileSync(sprites,'utf8');
  sp=once(sp,/case 'space_green':[\s\S]*?break;\n    default: break;/,`case 'space_green':\n      rect(ctx,bx+2,by-5,12,3,'#3c4d2b');rect(ctx,bx+1,by-2,14,5,'#53683a');rect(ctx,bx+3,by-3,10,1,'#71834a');\n      rect(ctx,bx+2,by,12,4,'#263128');rect(ctx,bx+3,by,10,3,'#c8862f');rect(ctx,bx+4,by,8,2,'#f2bb55');rect(ctx,bx+5,by,6,1,'#ffe18a');\n      rect(ctx,bx,by+1,3,5,'#3c4d2b');rect(ctx,bx+13,by+1,3,5,'#3c4d2b');rect(ctx,bx+1,by+7,14,8,'#465b34');\n      rect(ctx,bx+3,by+6,10,3,'#617642');rect(ctx,bx+4,by+9,8,5,'#2b3728');rect(ctx,bx+6,by+9,4,4,'#6f8447');\n      rect(ctx,bx,by+8,4,6,'#38482e');rect(ctx,bx+12,by+8,4,6,'#38482e');rect(ctx,bx+2,by+14,4,3,'#202923');rect(ctx,bx+10,by+14,4,3,'#202923');\n      rect(ctx,bx+7,by+11,2,2,'#f4d03f');px(ctx,bx+14,by+5,'#d6e06d',1);break;\n    default: break;`,'Jalo redesign');writeFileSync(sprites,sp);
}
