import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
const once=(s,re,to,label)=>{const n=s.replace(re,to);if(n===s)throw new Error('Gunfeel patch failed: '+label);return n;};
const ENGINE=`function gunfeelHash(id:string){let h=2166136261;for(let i=0;i<id.length;i++){h^=id.charCodeAt(i);h=Math.imul(h,16777619);}return Math.abs(h|0);}
function gunfeelColorFrom(id:string,type=''){const q=(id+' '+type).toLowerCase();if(q.includes('gold')||q.includes('coin')||q.includes('egg'))return '#f4d03f';if(q.includes('plasma')||q.includes('laser')||q.includes('quant')||q.includes('rayo'))return q.includes('quant')?'#b58cff':'#67d7e8';if(q.includes('toast')||q.includes('horno')||q.includes('fire')||q.includes('mustard'))return '#ff9f43';if(q.includes('butter')||q.includes('jarabe')||q.includes('mermelada'))return '#ffd95a';if(q.includes('bread')||q.includes('crumb')||q.includes('baguette')||q.includes('dough')||q.includes('miga')||q.includes('pan'))return '#e9bd72';const c=['#f5f0d7','#9fd9e4','#e49c8c','#c6a6e8','#b8d58b','#e6b875','#b7c4d0'];return c[gunfeelHash(id)%c.length];}
function gunfeelRecoilForce(w:any){const pellets=Math.max(1,w?.projectileCount??1),dmg=Math.max(1,w?.damage??1);return Math.min(.24,.045+dmg*.003+Math.min(5,pellets)*.012+(w?.continuous?-.025:0));}
function gunfeelMuzzle(engine:GameEngine,p:any,w:any,dx:number,dy:number){const id=String(w?.id??'weapon'),type=String(w?.projectileType??''),h=gunfeelHash(id),c=gunfeelColorFrom(id,type),mx=p.x+7+dx*11,my=p.y+8+dy*11,n=2+(h%3)+((w?.projectileCount??1)>=4?2:0);spawn(engine,mx,my,'spark',n,c);if(/bread|crumb|baguette|dough|miga|pan|toast/i.test(id+' '+type)&&!w?.continuous)spawn(engine,mx,my,'crumb',1+(h%2),'#e6bc78');const recoil=gunfeelRecoilForce(w);p.vx-=dx*recoil;p.vy-=dy*recoil;p.shootFlash=Math.max(p.shootFlash,w?.continuous?2:4);engine.shakeIntensity=Math.max(engine.shakeIntensity,w?.continuous?.12:Math.min(.75,.16+(w?.damage??1)*.012));}
function gunfeelEnemyHit(engine:GameEngine,e:Enemy,p:Projectile,damage:number,crit:boolean,content:RoomContent,preHp:number){if(preHp<=0)return;const w=p.sourceWeapon?WEAPONS[p.sourceWeapon]:undefined,killed=e.hp<=0,continuous=!!w?.continuous,heavy=damage>=18||(w?.projectileCount??1)>=5||(w?.knockback??0)>=3,dirLen=Math.hypot(p.vx,p.vy)||1,dx=p.vx/dirLen,dy=p.vy/dirLen,c=gunfeelColorFrom(String(p.sourceWeapon??p.type),String(p.type));let stop=killed?(e.isBoss?2:e.elite?4:3):crit?2:heavy?2:1;if(continuous&&engine.frame%5!==0)stop=0;if(stop>0)engine.hitStop=Math.max(engine.hitStop,stop);e.hurtTimer=Math.max(e.hurtTimer,crit?9:6);if(e.hp>0){const push=e.isBoss?.12:Math.min(.75,.18+Math.min(2.5,p.knockback??0)*.13+Math.min(20,damage)*.012);moveEnemy(e,currentRoomOf(engine),dx*push,dy*push);}const cx=e.x+e.size/2,cy=e.y+e.size/2;spawn(engine,cx,cy,'spark',crit?8:heavy?6:4,c);if(/bread|crumb|baguette|dough|miga|pan|toast/i.test(String(p.sourceWeapon??'')+' '+p.type))spawn(engine,cx,cy,'crumb',crit?4:2,'#e8be7a');engine.shakeIntensity=Math.max(engine.shakeIntensity,killed?(e.isBoss?2.2:1.7):crit?1.15:heavy?.8:.4);if(killed&&!e.isBoss){spawn(engine,cx,cy,'spark',e.elite?16:11,c);spawn(engine,cx,cy,'crumb',e.elite?8:5,'#d8dde3');}}
`;
const RENDER=`function gunfeelVisualHash(id:string){let h=0;for(let i=0;i<id.length;i++)h=(Math.imul(h,33)+id.charCodeAt(i))|0;return Math.abs(h);}
function gunfeelVisualColor(w:any){const id=String(w?.id??''),t=String(w?.projectileType??''),q=(id+' '+t).toLowerCase();if(q.includes('gold')||q.includes('coin')||q.includes('egg'))return '#f7d64b';if(q.includes('plasma')||q.includes('laser')||q.includes('rayo'))return '#6de1ef';if(q.includes('quant'))return '#ba92ff';if(q.includes('toast')||q.includes('horno')||q.includes('fire'))return '#ff9d45';if(q.includes('butter')||q.includes('jarabe')||q.includes('mermelada'))return '#ffe269';if(q.includes('bread')||q.includes('crumb')||q.includes('baguette')||q.includes('dough')||q.includes('miga')||q.includes('pan'))return '#efc77e';const cs=['#fff2bd','#b8e6ee','#efad9e','#d0b5ef','#c8df9e','#efc185','#cbd5dd'];return cs[gunfeelVisualHash(id)%cs.length];}
function gunfeelRecoilPx(w:any){return Math.min(4,1+Math.floor(((w?.damage??1)/12))+((w?.projectileCount??1)>=5?1:0));}
function drawGunfeelMuzzle(ctx:CanvasRenderingContext2D,engine:GameEngine){const p=engine.player;if(p.hp<=0||p.shootFlash<=0)return;const w=activeWeapon(p);if(!w)return;const a=aimVector(engine),ang=Math.atan2(a.y,a.x),h=gunfeelVisualHash(w.id),profile=h%5,size=2+((h>>3)%3),c=gunfeelVisualColor(w),mx=p.x+7+a.x*(17-gunfeelRecoilPx(w)),my=p.y+8+a.y*(17-gunfeelRecoilPx(w));ctx.save();ctx.translate(Math.round(mx),Math.round(my));ctx.rotate(ang);ctx.globalAlpha=Math.min(1,.45+p.shootFlash*.14);ctx.fillStyle=c;if(profile===0){ctx.fillRect(0,-1,7+size,3);ctx.fillRect(3,-3,3,7);}else if(profile===1){ctx.fillRect(0,-2,5+size,5);ctx.fillRect(5+size,-1,4,3);ctx.fillRect(2,-4,2,2);ctx.fillRect(2,3,2,2);}else if(profile===2){ctx.fillRect(0,-3,3,2);ctx.fillRect(0,2,3,2);ctx.fillRect(3,-2,5+size,4);}else if(profile===3){ctx.fillRect(0,-1,9+size,2);ctx.fillRect(2,-3,2,6);ctx.fillRect(7+size,-2,2,4);}else{ctx.fillRect(0,-2,4,4);ctx.fillRect(4,-3,3,6);ctx.fillRect(7,-1,4+size,2);}ctx.fillStyle='#fff8d8';ctx.globalAlpha*=.72;ctx.fillRect(0,-1,Math.max(2,size+1),2);ctx.restore();}
`;
export function applyDuckGunfeel(gameDir){
  const ef=path.join(gameDir,'game','engine.ts');let e=readFileSync(ef,'utf8');
  e=once(e,/export function updateEngine\(/,ENGINE+'\nexport function updateEngine(','helpers');
  e=once(e,"  spawn(engine,p.x+7+dx*10,p.y+8+dy*10,'spark',w.id==='breadcrumb_shotgun'?6:w.id==='vault_drill'?4:2,w.id==='golden_egg_revolver'?'#f4d03f':w.id==='butter_blaster'?'#ffd95a':'#fff3b0');","  gunfeelMuzzle(engine,p,w,dx,dy);",'muzzle/recoil');
  e=once(e,/        damageEnemy\(engine,e,final,crit,content\);/,"        const gunfeelPreHp=e.hp;damageEnemy(engine,e,final,crit,content);gunfeelEnemyHit(engine,e,p,final,crit,content,gunfeelPreHp);",'enemy impact');
  writeFileSync(ef,e);
  const rf=path.join(gameDir,'game','render.ts');let r=readFileSync(rf,'utf8');
  r=once(r,/function drawHeldWeapon\(ctx:CanvasRenderingContext2D,engine:GameEngine\)\{/,RENDER+'\nfunction drawHeldWeapon(ctx:CanvasRenderingContext2D,engine:GameEngine){','render helpers');
  r=once(r,'const aim=aimVector(engine),ang=Math.atan2(aim.y,aim.x),kick=p.shootFlash>0?2:0;','const aim=aimVector(engine),ang=Math.atan2(aim.y,aim.x),kick=p.shootFlash>0?gunfeelRecoilPx(w):0;','visual recoil');
  r=once(r,'if(heldBehind)drawHeldWeapon(ctx,engine);','if(heldBehind){drawHeldWeapon(ctx,engine);drawGunfeelMuzzle(ctx,engine);}','rear muzzle');
  r=once(r,'if(!heldBehind)drawHeldWeapon(ctx,engine);','if(!heldBehind){drawHeldWeapon(ctx,engine);drawGunfeelMuzzle(ctx,engine);}','front muzzle');
  writeFileSync(rf,r);
}
