import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
const once=(s,re,to,label)=>{const n=s.replace(re,to);if(n===s)throw new Error('Difficulty patch failed: '+label);return n;};
const DIFF_HELPERS=`export const DIFFICULTY_ORDER=['easy','normal','hard','mad'] as const;
export const DIFFICULTY_PROFILES={
  easy:{label:'FÁCIL',desc:'Más margen para aprender. Enemigos más lentos y menos agresivos.',hp:.82,dmg:.75,speed:.92,fire:1.18,count:.92,elite:.55,startHearts:1,floorHeal:2},
  normal:{label:'NORMAL',desc:'La experiencia actual de Duck Heist. Equilibrada y recomendada.',hp:1,dmg:1,speed:1,fire:1,count:1,elite:1,startHearts:0,floorHeal:1},
  hard:{label:'DIFÍCIL',desc:'Más presión, enemigos más resistentes y ataques más frecuentes.',hp:1.15,dmg:1.18,speed:1.06,fire:.88,count:1.1,elite:1.35,startHearts:0,floorHeal:.5},
  mad:{label:'LOCO POR EL PAN',desc:'El banco va a por ti. Máxima presión, más élites y casi sin respiro.',hp:1.28,dmg:1.38,speed:1.12,fire:.74,count:1.22,elite:1.75,startHearts:0,floorHeal:.5},
} as const;
let activeDifficulty:GameEngine['difficulty']='normal';
export function difficultyProfile(engine:GameEngine){return DIFFICULTY_PROFILES[engine.difficulty];}
export function difficultyLabel(engine:GameEngine){return difficultyProfile(engine).label;}
export function chooseDifficulty(engine:GameEngine,index:number){const i=Math.max(0,Math.min(DIFFICULTY_ORDER.length-1,index));const mode=DIFFICULTY_ORDER[i];engine.difficultyIndex=i;if(mode==='mad'&&!engine.madUnlocked){playDeny();return false;}engine.difficulty=mode;activeDifficulty=mode;return true;}
`;
const DIFF_UI=`function drawDifficultySkull(ctx:CanvasRenderingContext2D,x:number,y:number,col:string){ctx.save();ctx.fillStyle=col;ctx.fillRect(x+1,y,6,1);ctx.fillRect(x,y+1,8,4);ctx.fillRect(x+2,y+5,4,2);ctx.fillStyle='#10151c';ctx.fillRect(x+1,y+2,2,2);ctx.fillRect(x+5,y+2,2,2);ctx.fillRect(x+3,y+4,2,1);ctx.fillRect(x+3,y+6,1,1);ctx.fillRect(x+5,y+6,1,1);ctx.restore();}function drawDifficultyLock(ctx:CanvasRenderingContext2D,x:number,y:number,col:string){ctx.save();ctx.fillStyle=col;ctx.fillRect(x+1,y+4,9,7);ctx.fillRect(x+3,y+1,5,1);ctx.fillRect(x+2,y+2,2,3);ctx.fillRect(x+7,y+2,2,3);ctx.fillStyle='#11151c';ctx.fillRect(x+5,y+6,1,3);ctx.restore();}function renderDifficultyUI(engine:GameEngine){
  const ctx=engine.ui!,x=58,w=364,top=72,h=51,gap=5;
  drawPanel(ctx,30,22,420,306,'rgba(7,11,18,.94)','rgba(77,92,106,.72)','rgba(34,43,54,.72)');
  titleText(ctx,'ELIGE LA DIFICULTAD DEL ATRACO',240,46,14,'#f4d03f');
  text(ctx,'Puedes cambiarla al comenzar cada nueva partida.',240,60,5.8,'#7f919a','center');
  DIFFICULTY_ORDER.forEach((id,i)=>{
    const p=DIFFICULTY_PROFILES[id],y=top+i*(h+gap),on=engine.difficultyIndex===i,locked=id==='mad'&&!engine.madUnlocked;
    const col=locked?'#9a6570':id==='easy'?'#91d49b':id==='normal'?'#f4d03f':id==='hard'?'#f29a55':'#ff665e';const hoverFill=id==='easy'?'rgba(25,61,37,.95)':id==='normal'?'rgba(62,51,18,.95)':id==='hard'?'rgba(69,38,19,.95)':'rgba(69,22,28,.95)';
    ctx.save();if(on){ctx.shadowColor=col;ctx.shadowBlur=9;}
    drawPanel(ctx,x,y,w,h,on?hoverFill:'rgba(10,16,23,.82)',on?col:'rgba(71,84,97,.5)','rgba(35,45,55,.55)');ctx.restore();
    const labelX=x+18+(locked?16:0);if(locked)drawDifficultyLock(ctx,x+17,y+10,col);titleText(ctx,p.label,labelX,y+19,9,col,'left');const skullX=labelX+Math.min(126,p.label.length*5.8+8);for(let skull=0;skull<i+1;skull++)drawDifficultySkull(ctx,skullX+skull*11,y+11,col);
    wrappedText(ctx,locked?'Completa un atraco para desbloquearlo.':p.desc,x+18,y+31,w-36,5.5,6.4,2,locked?'#8a6870':'#8fa0aa');
    if(on){text(ctx,'›',x-10,y+29,13,col);text(ctx,'‹',x+w+10,y+29,13,col);}
  });
  text(ctx,engine.lastInput==='gamepad'?'CRUCETA · ELEGIR     A · CONFIRMAR     B · VOLVER':'W / S · ELEGIR     ENTER · CONFIRMAR     ESC · VOLVER',240,316,5.6,'#71858b','center');
}`;
export function applyDuckDifficulty(gameDir){
  const constants=path.join(gameDir,'game','constants.ts');let c=readFileSync(constants,'utf8');c=once(c,/  MENU = 'MENU',\n/,"  MENU = 'MENU',\n  DIFFICULTY = 'DIFFICULTY',\n",'state');writeFileSync(constants,c);
  const types=path.join(gameDir,'game','types.ts');let t=readFileSync(types,'utf8');t=once(t,/  menuIndex: number;\n/,"  difficulty:'easy'|'normal'|'hard'|'mad';\n  difficultyIndex:number;\n  madUnlocked:boolean;\n\n  menuIndex: number;\n",'engine fields');writeFileSync(types,t);
  const engine=path.join(gameDir,'game','engine.ts');let e=readFileSync(engine,'utf8');
  e=once(e,/export interface DiffScale \{\n  hp: number; dmg: number; speed: number; fire: number;\n  count: number; eliteChance: number; pattern: number;\n\}\n/,m=>m+'\n'+DIFF_HELPERS,'helpers');
  e=once(e,/export function floorScale\(floorIndex: number, roomDistance = 0\): DiffScale \{[\s\S]*?\n\}/,`export function floorScale(floorIndex:number,roomDistance=0):DiffScale{\n  const f=floorIndex,depth=Math.min(roomDistance,8)*.06,p=DIFFICULTY_PROFILES[activeDifficulty];\n  const hp=1+f*.11+depth*.5,dmg=1+f*.09,speed=1+f*.05,fire=Math.max(.55,1-f*.07),count=1+f*.22+depth;\n  const eliteChance=f<=1?(f===1?.10:0):Math.min(.42,.14+f*.09+depth*.5);\n  return {hp:hp*p.hp,dmg:dmg*p.dmg,speed:speed*p.speed,fire:Math.max(.42,Math.min(1.28,fire*p.fire)),count:count*p.count,eliteChance:eliteChance===0?0:Math.min(.65,eliteChance*p.elite),pattern:f};\n}`,'floor scale');
  e=once(e,/  let bestFloor=0;\n/,"  let bestFloor=0;\n  let madUnlocked=false;\n",'unlock init');
  e=once(e,/  setVolumes\(settings\.master, settings\.music, settings\.sfx\);/,"  try{madUnlocked=localStorage.getItem('duckheist_mad_bread_unlocked')==='1'||unlockedSkins.includes('golden');}catch{madUnlocked=unlockedSkins.includes('golden');}\n\n  setVolumes(settings.master, settings.music, settings.sfx);",'unlock load');
  e=once(e,/    menuIndex: 0, pauseIndex: 0, settingsIndex: 0, upgradeIndex: 0, wardrobeIndex: 0,/,"    difficulty:'normal',difficultyIndex:1,madUnlocked,\n    menuIndex: 0, pauseIndex: 0, settingsIndex: 0, upgradeIndex: 0, wardrobeIndex: 0,",'engine init');
  e=once(e,/export function startGame\(engine: GameEngine\) \{\n  saveProgress\(engine\);/,"export function startGame(engine: GameEngine) {\n  activeDifficulty=engine.difficulty;\n  saveProgress(engine);",'run difficulty');
  e=once(e,/  engine\.player = createPlayer\(engine\.metaLevels\);/,"  engine.player=createPlayer(engine.metaLevels);\n  const diff=DIFFICULTY_PROFILES[engine.difficulty];if(diff.startHearts>0){engine.player.maxHp+=diff.startHearts;engine.player.hp+=diff.startHearts;}",'easy heart');
  e=once(e,/    engine\.totalGoldenCrumbs\+=100;engine\.run\.goldenEarned\+=100;engine\.stats\.goldenCrumbs\+=100;/,"    engine.totalGoldenCrumbs+=100;engine.run.goldenEarned+=100;engine.stats.goldenCrumbs+=100;\n    engine.madUnlocked=true;try{localStorage.setItem('duckheist_mad_bread_unlocked','1');}catch{}",'victory unlock');
  e=once(e,/  engine\.player\.hp = Math\.min\(engine\.player\.maxHp, engine\.player\.hp \+ 1\);/,"  engine.player.hp=Math.min(engine.player.maxHp,engine.player.hp+DIFFICULTY_PROFILES[engine.difficulty].floorHeal);",'floor heal');
  e=e.replace(/const enraged=pct<\.52;/,"const enraged=pct<(engine.difficulty==='easy'?.45:engine.difficulty==='hard'?.57:engine.difficulty==='mad'?.62:.52);");
  e=e.replace(/const phase=pct<\.34\?2:pct<\.68\?1:0;/,"const phase=pct<(engine.difficulty==='easy'?.30:engine.difficulty==='hard'?.38:engine.difficulty==='mad'?.42:.34)?2:pct<(engine.difficulty==='easy'?.62:engine.difficulty==='hard'?.72:engine.difficulty==='mad'?.76:.68)?1:0;");
  writeFileSync(engine,e);
  const render=path.join(gameDir,'game','render.ts');let r=readFileSync(render,'utf8');
  r=once(r,/import \{ activeWeapon, currentRoomOf, getContentOf, SETTING_ROWS, settingValue, shopPrice \} from '\.\/engine';/,"import { activeWeapon,currentRoomOf,getContentOf,SETTING_ROWS,settingValue,shopPrice,DIFFICULTY_ORDER,DIFFICULTY_PROFILES,difficultyLabel } from './engine';",'render engine import');
  r=once(r,/function renderMenuUI\(engine: GameEngine\) \{/,DIFF_UI+'\n\nfunction renderMenuUI(engine: GameEngine) {','difficulty ui');
  r=once(r,/if\(s===GameState\.MENU \|\| s===GameState\.HEIST_INTRO\) \{/,"if(s===GameState.MENU || s===GameState.DIFFICULTY || s===GameState.HEIST_INTRO) {",'difficulty world');
  r=once(r,/    case GameState\.MENU: renderMenuUI\(engine\); break;/,"    case GameState.MENU: renderMenuUI(engine); break;\n    case GameState.DIFFICULTY: renderDifficultyUI(engine); break;",'render switch');
  r=once(r,/function renderPausedUI\(engine: GameEngine\) \{([\s\S]*?)text\(ctx,`SEMILLA · \$\{engine\.run\.seed\}`/,m=>m.replace("text(ctx,`SEMILLA · ${engine.run.seed}`","text(ctx,'DIFICULTAD',240,282,5.2,'#697882','center');text(ctx,difficultyLabel(engine),240,292,6.2,'#d9bd70','center',true);\n  text(ctx,`SEMILLA · ${engine.run.seed}`"),'pause label');
  r=once(r,/  const r = engine\.run, s = engine\.stats;\n  const lines:/,"  const r=engine.run,s=engine.stats;\n  text(ctx,'DIFICULTAD',70,130,5.5,'#8792a5','left');text(ctx,difficultyLabel(engine),CANVAS_WIDTH-70,130,6.5,'#e3bd6b','right',true);\n  const lines:",'victory label');
  writeFileSync(render,r);
  const app=path.join(gameDir,'App.tsx');let a=readFileSync(app,'utf8');
  a=once(a,/  createEngine, startGame, beginHeist, updateEngine, menuMove, buyUpgrade, saveSettings,getContentOf,/,"  createEngine,startGame,beginHeist,updateEngine,menuMove,buyUpgrade,saveSettings,getContentOf,chooseDifficulty,DIFFICULTY_ORDER,",'app imports');
  a=once(a,/const OVER_TOP = CANVAS_HEIGHT - 62, OVER_H = 22, OVER_GAP = 4, OVER_W = 200;/,"const OVER_TOP=CANVAS_HEIGHT-62,OVER_H=22,OVER_GAP=4,OVER_W=200;\nconst DIFF_TOP=72,DIFF_H=51,DIFF_GAP=5,DIFF_W=364;",'app constants');
  a=once(a,/    const inSwap = \(\) => !!engine\.swap;\n/,"    const inSwap=()=>!!engine.swap;\n    const moveDifficulty=(delta:number)=>{engine.difficultyIndex=(engine.difficultyIndex+delta+DIFFICULTY_ORDER.length)%DIFFICULTY_ORDER.length;playUiMove();force(n=>n+1);};\n    const confirmDifficulty=()=>{if(chooseDifficulty(engine,engine.difficultyIndex)){playUiSelect();beginHeist(engine);}};\n",'app helpers');
  a=once(a,/        case 0: beginHeist\(engine\); break;/,"        case 0: engine.difficultyIndex=Math.max(0,DIFFICULTY_ORDER.indexOf(engine.difficulty));goTo(GameState.DIFFICULTY);break;",'menu start');
  a=once(a,/        case GameState\.MENU:\n          if \(up\) menuMove\(engine, -1, 6, 'menu'\);\n          else if \(down\) menuMove\(engine, 1, 6, 'menu'\);\n          else if \(yes\) activateMenu\(\);\n          break;/,`        case GameState.MENU:\n          if(up)menuMove(engine,-1,6,'menu');else if(down)menuMove(engine,1,6,'menu');else if(yes)activateMenu();break;\n        case GameState.DIFFICULTY:\n          if(up)moveDifficulty(-1);else if(down)moveDifficulty(1);else if(yes)confirmDifficulty();else if(k==='escape'){playUiBack();goTo(GameState.MENU);}break;`,'difficulty keys');
  a=once(a,/      if \(st === GameState\.MENU \|\| st === GameState\.PAUSED \|\| st === GameState\.GAME_OVER \|\| st === GameState\.VICTORY\) \{[\s\S]*?        \}\n      \} else if \(st === GameState\.SETTINGS\) \{/,`      if(st===GameState.MENU||st===GameState.DIFFICULTY||st===GameState.PAUSED||st===GameState.GAME_OVER||st===GameState.VICTORY){\n        const top=st===GameState.MENU?MENU_TOP:st===GameState.DIFFICULTY?DIFF_TOP:st===GameState.PAUSED?PAUSE_TOP:OVER_TOP;\n        const cnt=st===GameState.MENU?6:st===GameState.DIFFICULTY?4:st===GameState.PAUSED?PAUSE_MENU.count:2;\n        const h=st===GameState.MENU?MENU_H:st===GameState.DIFFICULTY?DIFF_H:st===GameState.PAUSED?PAUSE_H:OVER_H;\n        const g=st===GameState.MENU?MENU_GAP:st===GameState.DIFFICULTY?DIFF_GAP:st===GameState.PAUSED?PAUSE_GAP:OVER_GAP;\n        const w=st===GameState.MENU?MENU_W:st===GameState.DIFFICULTY?DIFF_W:st===GameState.PAUSED?PAUSE_W:OVER_W;\n        const i=st===GameState.MENU?mainMenuHit(p.x,p.y):hitList(p.x,p.y,top,cnt,h,g,w);\n        if(i>=0){if(st===GameState.MENU){if(engine.menuIndex!==i){engine.menuIndex=i;softMove();}}else if(st===GameState.DIFFICULTY){if(engine.difficultyIndex!==i){engine.difficultyIndex=i;softMove();}}else if(st===GameState.PAUSED){if(engine.pauseIndex!==i){engine.pauseIndex=i;softMove();}}else if(engine.pauseIndex!==i){engine.pauseIndex=i;softMove();}}\n      } else if(st===GameState.SETTINGS){`,'difficulty hover');
  a=once(a,/        case GameState\.MENU: \{\n          setMusic\('menu'\);const i=mainMenuHit\(x,y\);\n          if \(i >= 0\) \{ engine\.menuIndex = i; activateMenu\(\); \}\n          break;\n        \}/,`        case GameState.MENU:{setMusic('menu');const i=mainMenuHit(x,y);if(i>=0){engine.menuIndex=i;activateMenu();}break;}\n        case GameState.DIFFICULTY:{const i=hitList(x,y,DIFF_TOP,4,DIFF_H,DIFF_GAP,DIFF_W);if(i>=0){engine.difficultyIndex=i;confirmDifficulty();}else{playUiBack();goTo(GameState.MENU);}break;}`,'difficulty click');
  a=once(a,/case GameState\.MENU:\s*return (?:translateText\()?['\"]W \/ S elegir · ENTER confirmar · rueda también vale['\"]\)?;/,"case GameState.MENU:return translateText('W / S elegir · ENTER confirmar · rueda también vale');\n    case GameState.DIFFICULTY:return translateText('W / S dificultad · ENTER confirmar · ESC volver');",'difficulty hint');
  writeFileSync(app,a);
}
