import { readFileSync,writeFileSync } from 'node:fs';
import path from 'node:path';

function replaceOnce(src,from,to,label){const i=src.indexOf(from);if(i<0)throw new Error('Direct rewards patch failed: '+label);if(src.indexOf(from,i+from.length)>=0)throw new Error('Direct rewards patch failed: '+label+' is not unique');return src.slice(0,i)+to+src.slice(i+from.length);}
function functionRange(src,signature,label){const start=src.indexOf(signature);if(start<0)throw new Error('Direct rewards patch failed: '+label+' signature');const brace=src.indexOf('{',start);if(brace<0)throw new Error('Direct rewards patch failed: '+label+' opening brace');let depth=0,quote='',escaped=false,lineComment=false,blockComment=false;for(let i=brace;i<src.length;i++){const ch=src[i],nx=src[i+1];if(lineComment){if(ch==='\n')lineComment=false;continue;}if(blockComment){if(ch==='*'&&nx==='/'){blockComment=false;i++;}continue;}if(quote){if(escaped){escaped=false;continue;}if(ch==='\\'){escaped=true;continue;}if(ch===quote)quote='';continue;}if(ch==='/'&&nx==='/'){lineComment=true;i++;continue;}if(ch==='/'&&nx==='*'){blockComment=true;i++;continue;}if(ch==='\''||ch==='"'||ch==='`'){quote=ch;continue;}if(ch==='{')depth++;else if(ch==='}'){depth--;if(depth===0)return{start,end:i+1};}}throw new Error('Direct rewards patch failed: '+label+' closing brace');}
const GREEK_ENGINE=`function greekItemPedestals(content:any){const out:any[]=[];const main=content.pedestal;if(main&&!main.taken)out.push(main);if(!content.choiceTaken)for(const p of content.choices??[])if(p&&!p.taken&&!out.includes(p))out.push(p);return out;}
function greekPedestalBaseRect(ped:any){const cx=Math.round(ped.x+12),top=Math.round(ped.y+12);return{x:cx-8,y:top+4,w:16,h:3};}
function greekResolvePlayerBase(body:any,r:{x:number;y:number;w:number;h:number}){const a=bankFootRect(body,14,16);if(!bankRectsOverlap(a,r))return false;const left=a.x+a.w-r.x,right=r.x+r.w-a.x,up=a.y+a.h-r.y,down=r.y+r.h-a.y,cands=[{d:left,x:-(left+.75),y:0},{d:right,x:right+.75,y:0},{d:up,x:0,y:-(up+.75)},{d:down,x:0,y:down+.75}].filter(q=>q.d>0).sort((u,v)=>u.d-v.d);if(!cands.length)return false;const q=cands[0];body.x+=q.x;body.y+=q.y;if(q.x&&typeof body.vx==='number')body.vx=0;if(q.y&&typeof body.vy==='number')body.vy=0;return true;}
function resolveGreekItemPedestalCollision(engine:GameEngine){const room=currentRoomOf(engine);if(room.type!==RoomType.ITEM)return;const content=getContentOf(engine,room),c:any=content,peds=greekItemPedestals(content);if(!peds.length)return;const pl=engine.player,foot=bankFootRect(pl,14,16),cx=foot.x+foot.w/2,cy=foot.y+foot.h/2,prevX=c.greekPedPrevX??cx,prevY=c.greekPedPrevY??cy;for(const ped of peds){const r=greekPedestalBaseRect(ped),a=bankFootRect(pl,14,16);if(pl.dashTimer>0&&!bankRectsOverlap(a,r)&&bankSegmentRect(prevX,prevY,cx,cy,r,1)){const dx=cx-prevX,dy=cy-prevY,len=Math.hypot(dx,dy)||1;pl.x-=dx+dx/len*.75;pl.y-=dy+dy/len*.75;pl.vx=0;pl.vy=0;break;}greekResolvePlayerBase(pl,r);}const af=bankFootRect(pl,14,16);c.greekPedPrevX=af.x+af.w/2;c.greekPedPrevY=af.y+af.h/2;}`;
const GREEK_VIS=`function drawGreekItemPedestal(ctx:CanvasRenderingContext2D,ped:Pedestal,f:number,engine:GameEngine){if(ped.taken)return;const cx=Math.round(ped.x+12),y=Math.round(ped.y+12),floor=Math.max(0,Math.min(5,engine.map.floorIndex)),marble=floor>=4?'#eee3ce':'#e7e0d2',hi=floor>=4?'#fff6df':'#f8f3e8',shade=floor>=4?'#b9aa91':'#bcb6aa',edge=floor>=4?'#5a4b3a':'#555b60',gold=floor>=3?'#d6ad43':'#b89545';ctx.save();ctx.fillStyle='rgba(0,0,0,.22)';ctx.fillRect(cx-10,y+7,20,2);ctx.fillStyle=edge;ctx.fillRect(cx-9,y+5,18,2);ctx.fillStyle=shade;ctx.fillRect(cx-8,y+4,16,2);ctx.fillStyle=marble;ctx.fillRect(cx-7,y+4,14,1);ctx.fillStyle=edge;ctx.fillRect(cx-5,y+2,10,3);ctx.fillStyle=marble;ctx.fillRect(cx-4,y+1,8,4);ctx.fillStyle=hi;ctx.fillRect(cx-3,y+1,2,3);ctx.fillStyle=edge;ctx.fillRect(cx-7,y,14,2);ctx.fillStyle=marble;ctx.fillRect(cx-6,y-1,12,2);ctx.fillStyle=hi;ctx.fillRect(cx-4,y-1,8,1);ctx.fillStyle=gold;ctx.fillRect(cx-5,y+1,10,1);if(Math.sin(f*.075+ped.x*.03)>.7){ctx.fillStyle='#fff1a8';ctx.fillRect(cx+4,y,1,1);}ctx.restore();}
function visibleGreekItemPedestals(content:any){const out:any[]=[];const main=content.pedestal;if(main&&!main.taken)out.push(main);if(!content.choiceTaken)for(const p of content.choices??[])if(p&&!p.taken&&!out.includes(p))out.push(p);return out;}
function drawSpecialRoomPedestalLayer(ctx:CanvasRenderingContext2D,content:any,f:number,engine:GameEngine){const room=currentRoomOf(engine);if(room.type===RoomType.ITEM){for(const ped of visibleGreekItemPedestals(content))drawGreekItemPedestal(ctx,ped,f,engine);}else if(room.type===RoomType.EVENT&&!content.cafe&&content.event){const event=content.event;drawPedestal(ctx,event.x-4,event.y+9,f,event.used,eventPedestalColor(event.kind));}}
function greekRewardOccludesPlayer(ped:any,pl:any){if(ped.taken)return false;const cx=Math.round(ped.x+12),y=Math.round(ped.y+12),feet=pl.y+15,baseY=y+4;return pl.x+20>cx-17&&pl.x-6<cx+17&&pl.y+22>ped.y-18&&pl.y-10<y+10&&feet<baseY+3;}
function drawItemRoomRewardForeground(ctx:CanvasRenderingContext2D,content:any,f:number,engine:GameEngine,pl:any){if(currentRoomOf(engine).type!==RoomType.ITEM)return;for(const ped of visibleGreekItemPedestals(content)){if(!greekRewardOccludesPlayer(ped,pl))continue;ctx.save();ctx.beginPath();ctx.rect(pl.x-9,pl.y-11,32,36);ctx.clip();drawGreekItemPedestal(ctx,ped,f,engine);drawPedestalFull(ctx,ped,f,engine);ctx.restore();}}`;
function replaceGenericPedestal(fn){const needle='drawPedestal(';const call=fn.indexOf(needle);if(call<0)throw new Error('Direct rewards patch failed: generic pedestal call not found');if(fn.indexOf(needle,call+needle.length)>=0)throw new Error('Direct rewards patch failed: multiple generic pedestal calls inside drawPedestalFull');let quote='',escaped=false,depth=0,end=-1;for(let i=call;i<fn.length;i++){const ch=fn[i];if(quote){if(escaped){escaped=false;continue;}if(ch==='\\'){escaped=true;continue;}if(ch===quote)quote='';continue;}if(ch==='\''||ch==='"'||ch==='`'){quote=ch;continue;}if(ch==='(')depth++;else if(ch===')'){depth--;if(depth===0){let j=i+1;while(j<fn.length&&/\s/.test(fn[j]))j++;if(fn[j]===';')j++;end=j;break;}}}if(end<0)throw new Error('Direct rewards patch failed: could not isolate generic pedestal statement');return fn.slice(0,call)+fn.slice(end);}
function stripResidualGenericPedestals(src){let at=0;while((at=src.indexOf('drawPedestal(',at))>=0){if(src.slice(Math.max(0,at-9),at)==='function '){at+=13;continue;}const end=src.indexOf(');',at);if(end<0)break;src=src.slice(0,at)+src.slice(end+2);}return src;}
export function applyDuckDirectRewards(gameDir){const engineFile=path.join(gameDir,'game','engine.ts');let e=readFileSync(engineFile,'utf8');e=replaceOnce(e,'export function updateEngine(',GREEK_ENGINE+'\nexport function updateEngine(','engine helpers');e=replaceOnce(e,'export function updateBankProps(engine:GameEngine){if(engine.state!==GameState.PLAYING)return;','export function updateBankProps(engine:GameEngine){if(engine.state!==GameState.PLAYING)return;resolveGreekItemPedestalCollision(engine);','pillar collision hook');e=replaceOnce(e,'    const close=dist(ped.x+12,ped.y,player.x+7,player.y+8)<28;','    const close=dist(ped.x+12,ped.y+(currentRoomOf(engine).type===RoomType.ITEM?9:0),player.x+7,player.y+8)<(currentRoomOf(engine).type===RoomType.ITEM?30:28);','main reward pickup reach');e=replaceOnce(e,'      const ped=content.choices[i],close=!ped.taken&&dist(ped.x+12,ped.y,player.x+7,player.y+8)<28;','      const ped=content.choices[i],close=!ped.taken&&dist(ped.x+12,ped.y+(currentRoomOf(engine).type===RoomType.ITEM?9:0),player.x+7,player.y+8)<(currentRoomOf(engine).type===RoomType.ITEM?30:28);','choice reward pickup reach');writeFileSync(engineFile,e);
const file=path.join(gameDir,'game','render.ts');let src=readFileSync(file,'utf8');const signature='function drawPedestalFull(ctx: CanvasRenderingContext2D, ped: Pedestal, f: number, engine: GameEngine) {';const range=functionRange(src,signature,'drawPedestalFull');const original=src.slice(range.start,range.end),patched=replaceGenericPedestal(original);if(patched===original)throw new Error('Direct rewards patch failed: no change');src=src.slice(0,range.start)+GREEK_VIS+'\n'+patched+src.slice(range.end);src=replaceOnce(src,'  drawBankProps(ctx,content,f,engine.map.floorIndex);','  drawBankProps(ctx,content,f,engine.map.floorIndex);\n  drawSpecialRoomPedestalLayer(ctx,content,f,engine);','special pedestal base layer');src=replaceOnce(src,'    drawBankPropsForeground(ctx,content,f,p,engine.map.floorIndex);','    drawBankPropsForeground(ctx,content,f,p,engine.map.floorIndex);\n    drawItemRoomRewardForeground(ctx,content,f,engine,p);','item reward foreground depth');src=stripResidualGenericPedestals(src);writeFileSync(file,src);}
