import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
const once=(s,re,to,label)=>{const n=s.replace(re,to);if(n===s)throw new Error('Pedestal station patch failed: '+label);return n;};
const VIS=`function eventPedestalColor(kind:string){return kind==='security_terminal'?'#61c9ff':kind==='field_medic'?'#77e39a':kind==='weapon_forge'?'#f29a55':kind==='bread_altar'?'#b06ce3':'#f4d03f';}
function drawEventPedestalAccent(ctx:CanvasRenderingContext2D,event:{kind:string;x:number;y:number;used:boolean},f:number){if(event.used)return;const x=event.x,y=event.y+10,k=event.kind;ctx.save();ctx.globalAlpha=.72+.18*Math.sin(f*.08);if(k==='security_terminal'){ctx.fillStyle='#61c9ff';ctx.fillRect(x-8,y+4,3,8);ctx.fillRect(x+13,y+4,3,8);}else if(k==='field_medic'){ctx.fillStyle='#77e39a';ctx.fillRect(x+1,y+5,10,3);ctx.fillRect(x+4,y+2,3,9);}else if(k==='weapon_forge'){ctx.fillStyle='#f29a55';ctx.fillRect(x-8,y+3,3,13);ctx.fillRect(x+13,y+3,3,13);}else if(k==='bread_altar'){ctx.fillStyle='#b06ce3';ctx.fillRect(x-7,y+9,2,7);ctx.fillRect(x+12,y+7,2,9);ctx.fillStyle='#dfb0ff';ctx.fillRect(x-6,y+6,1,3);ctx.fillRect(x+13,y+4,1,3);}ctx.restore();}`;
export function applyDuckPedestalStations(gameDir){
 const types=path.join(gameDir,'game','types.ts');let t=readFileSync(types,'utf8');t=once(t,/export type EventKind = 'safe'\|'bakery'\|'vending'\|'injured'\|'interrogation'\|'atm';/,"export type EventKind='safe'|'bakery'|'vending'|'injured'|'interrogation'|'atm'|'security_terminal'|'field_medic'|'weapon_forge'|'bread_altar';",'event kinds');writeFileSync(types,t);
 const events=path.join(gameDir,'game','events.ts');let v=readFileSync(events,'utf8');v=once(v,/  atm:\{name:'CAJERO ROTO',description:'12 migajas: 35% de ganar 8 monedas doradas\.',options:\['PROBAR · 12','PASAR'\],icon:'clandestine_account'\},\n};/,`  atm:{name:'CAJERO ROTO',description:'12 migajas: 35% de ganar 8 monedas doradas.',options:['PROBAR · 12','PASAR'],icon:'clandestine_account'},\n  security_terminal:{name:'PEDESTAL DE SEGURIDAD',description:'12 migajas: reduce la alerta y revela al jefe del piso.',options:['INTERVENIR · 12','DEJARLO'],icon:'vault_map'},\n  field_medic:{name:'PEDESTAL MÉDICO',description:'10 migajas: recupera 1 corazón si estás herido.',options:['CURAR · 10','PASAR'],icon:'bread_helmet'},\n  weapon_forge:{name:'PEDESTAL DEL ARSENAL',description:'24 migajas: fabrica un arma aleatoria para recoger.',options:['FABRICAR · 24','PASAR'],icon:'golden_beak'},\n  bread_altar:{name:'ALTAR DE LA MIGA',description:'Entrega 1 corazón por una recompensa de jefe.',options:['OFRECER 1 CORAZÓN','ALEJARSE'],icon:'holy_crumb'},\n};`,'events');writeFileSync(events,v);
 const engine=path.join(gameDir,'game','engine.ts');let e=readFileSync(engine,'utf8');e=once(e,/  const cost=event\.kind==='safe'\?18:event\.kind==='vending'\?8:event\.kind==='atm'\?12:event\.kind==='interrogation'\?15:0;/,"  const cost=event.kind==='safe'?18:event.kind==='vending'?8:event.kind==='atm'?12:event.kind==='interrogation'?15:event.kind==='security_terminal'?12:event.kind==='field_medic'?10:event.kind==='weapon_forge'?24:0;",'costs');e=once(e,/  if\(\(event\.kind==='bakery'\|\|event\.kind==='injured'\) && p\.hp<=1\) \{event\.message='Necesitas más de un corazón\.';playDeny\(\);return;\}/,"  if((event.kind==='bakery'||event.kind==='injured'||event.kind==='bread_altar')&&p.hp<=1){event.message='Necesitas más de un corazón.';playDeny();return;}\n  if(event.kind==='field_medic'&&p.hp>=p.maxHp){event.message='Ya estás al máximo.';playDeny();return;}",'guards');e=once(e,/    case 'atm':\n      if\(Math\.random\(\)<\.35\) \{awardGolden\(engine,8\);event\.message='¡Error bancario a tu favor!';\}\n      else \{content\.pickups\.push\(\{x:240,y:143,type:'crumb',value:4,lifetime:99999\}\);event\.message='Solo devuelve 4 migajas\. Típico\.';\}break;/,`    case 'atm':\n      if(Math.random()<.35){awardGolden(engine,8);event.message='¡Error bancario a tu favor!';}\n      else{content.pickups.push({x:240,y:143,type:'crumb',value:4,lifetime:99999});event.message='Solo devuelve 4 migajas. Típico.';}break;\n    case 'security_terminal':{changeAlert(engine,-25);const boss=[...engine.map.rooms.values()].find(r=>r.type===RoomType.BOSS);if(boss)boss.revealed=true;event.message='Cámaras anuladas. Objetivo localizado.';break;}\n    case 'field_medic':healPlayer(engine,1);event.message='Vendaje rápido. Nada de preguntas.';break;\n    case 'weapon_forge':content.pedestal={x:300,y:142,itemId:rollWeapon(engine,true),isWeapon:true,taken:false,rise:0};event.message='El arsenal imprimió algo ilegal.';break;\n    case 'bread_altar':p.hp--;content.pedestal={x:300,y:142,itemId:rollBossRewardItem(engine),isWeapon:false,taken:false,rise:0};event.message='La miga aceptó el trato.';break;`,'effects');writeFileSync(engine,e);
 const render=path.join(gameDir,'game','render.ts');let r=readFileSync(render,'utf8');r=once(r,/function drawPedestalFull\(ctx: CanvasRenderingContext2D, ped: Pedestal, f: number, engine: GameEngine\) \{/,VIS+'\n\nfunction drawPedestalFull(ctx: CanvasRenderingContext2D, ped: Pedestal, f: number, engine: GameEngine) {','visual helper');r=once(r,/    drawPedestal\(ctx,event\.x-4,event\.y\+9,f,event\.used\);/,"    drawPedestal(ctx,event.x-4,event.y+9,f,event.used,eventPedestalColor(event.kind));\n    drawEventPedestalAccent(ctx,event,f);",'visuals');writeFileSync(render,r);
}
