const EN:Record<string,string>={
'DUCK HEIST':'DUCK HEIST',
'EL BANCO DEL PAN':'THE BREAD BANK',
'¡EL PRECIO DEL PAN ES UN ROBO!':'THE PRICE OF BREAD IS ROBBERY!',
'INICIAR ATRACO':'START HEIST',
'MEJORAS':'UPGRADES',
'ARMARIO':'WARDROBE',
'COLECCIÓN':'COLLECTION',
'CÓMO JUGAR':'HOW TO PLAY',
'CONFIGURACIÓN':'SETTINGS',
'W/S o FLECHAS para elegir · ENTER para confirmar':'W/S or ARROWS to choose · ENTER to confirm',
'PAUSA':'PAUSED',
'CONTINUAR':'RESUME',
'REINICIAR PARTIDA':'RESTART RUN',
'MENÚ PRINCIPAL':'MAIN MENU',
'Presiona ESC para continuar':'Press ESC to resume',
'CONTROLES':'CONTROLS',
'Moverse':'Move',
'Disparar':'Shoot',
'Apuntar y disparar':'Aim and shoot',
'Esquivar':'Dash',
'Objeto activo':'Active item',
'Interactuar':'Interact',
'Mantener para reiniciar':'Hold to restart',
'Pausa':'Pause',
'ESPACIO':'SPACE',
'Limpia cada sala de policías para abrir las puertas.':'Clear every room of police to open the doors.',
'Recoge migajas para comprar en la tienda.':'Collect crumbs to buy things in the shop.',
'Puerta DORADA = sala de objetos · PLATEADA = sala normal.':'GOLD door = item room · SILVER door = normal room.',
'Puerta ROJA Y NEGRA = el JEFE del piso.':'RED AND BLACK door = the floor BOSS.',
'Llevas DOS armas: usa la RUEDA DEL MOUSE para cambiar.':'You carry TWO weapons: use the MOUSE WHEEL to switch.',
'Derrota al jefe, recoge su botín y baja por las escaleras.':'Defeat the boss, collect the loot, and go down the stairs.',
'Cada piso es más duro y el mapa cambia en cada atraco.':'Each floor is harder and the map changes every heist.',
'Corazones = vida. El pan te cura. Si llegan a cero, pierdes.':'Hearts = health. Bread heals you. If they reach zero, you lose.',
'VOLVER':'BACK',
'ENTER o ESC para volver':'ENTER or ESC to go back',
'VOLUMEN GENERAL':'MASTER VOLUME',
'MÚSICA':'MUSIC',
'EFECTOS DE SONIDO':'SOUND EFFECTS',
'VIBRACIÓN DE PANTALLA':'SCREEN SHAKE',
'NÚMEROS DE DAÑO':'DAMAGE NUMBERS',
'ESCALA DE INTERFAZ':'UI SCALE',
'PANTALLA COMPLETA':'FULLSCREEN',
'BRILLO':'BRIGHTNESS',
'PROBAR CUAC':'TEST QUACK',
'PROBAR ESQUIVE':'TEST DASH',
'IDIOMA':'LANGUAGE',
'SÍ':'YES',
'NO':'NO',
'REPRODUCIR':'PLAY',
'FLECHAS · AJUSTAR     ENTER · PROBAR     ESC · VOLVER':'ARROWS · ADJUST     ENTER · TEST     ESC · BACK',
'CRUCETA · AJUSTAR     A · PROBAR     B · VOLVER':'D-PAD · ADJUST     A · TEST     B · BACK',
'REBANADA DE PAN':'BREAD SLICE',
'SÁNDWICH COMPLETO':'FULL SANDWICH',
'SÁNDWICH':'SANDWICH',
'MIGAJAS':'CRUMBS',
'MONEDAS DORADAS':'GOLDEN COINS',
'PRECIO':'PRICE',
'COMPRAR':'BUY',
'EQUIPAR ASPECTO':'EQUIP ASPECT',
'EQUIPADO':'EQUIPPED',
'DESBLOQUEADO':'UNLOCKED',
'DISPONIBLE':'AVAILABLE',
'COMPRAR ASPECTO':'BUY ASPECT',
'ASPECTOS':'ASPECTS',
'Recupera 1 corazón.':'Restores 1 heart.',
'Recupera 2 corazones.':'Restores 2 hearts.',
'Recupera 3 corazones.':'Restores 3 hearts.',
'Recupera toda la vida.':'Restores all health.',
'Recupera 1 corazón y te da un empujón de velocidad.':'Restores 1 heart and gives you a speed boost.',
'SINERGIA DESCUBIERTA':'SYNERGY DISCOVERED',
'SALA DESPEJADA':'ROOM CLEARED',
'Piso alcanzado':'Floor reached',
'Jefes derrotados':'Bosses defeated',
'Objetos encontrados':'Items found',
'Armas encontradas':'Weapons found',
'Daño infligido':'Damage dealt',
'Daño recibido':'Damage taken',
'Duración':'Duration',
'ARMA':'WEAPON',
'ARMA ACTIVA':'ACTIVE WEAPON',
'VACÍO':'EMPTY',
'INVENTARIO LLENO':'INVENTORY FULL',
'¿QUÉ ARMA QUIERES REEMPLAZAR?':'WHICH WEAPON DO YOU WANT TO REPLACE?',
'ARMA EN EL SUELO':'WEAPON ON THE FLOOR',
'TUS ARMAS':'YOUR WEAPONS',
'ESC · CANCELAR':'ESC · CANCEL',
'1 / 2 · ELEGIR · E CONFIRMAR':'1 / 2 · CHOOSE · E CONFIRM',
'RUEDA DEL MOUSE · CAMBIAR ARMA':'MOUSE WHEEL · SWITCH WEAPON',
'CAMBIAR ARMA':'SWITCH WEAPON',
'DAÑO':'DAMAGE',
'CADENCIA DE DISPARO':'FIRE RATE',
'ALCANCE':'RANGE',
'VELOCIDAD DE PROYECTIL':'PROJECTILE SPEED',
'Especial':'Special',
'COMÚN':'COMMON',
'POCO COMÚN':'UNCOMMON',
'RARO':'RARE',
'ÉPICO':'EPIC',
'LEGENDARIO':'LEGENDARY',
'BOTÍN DEL JEFE':'BOSS LOOT',
'E · BAJAR AL SIGUIENTE PISO':'E · GO TO NEXT FLOOR',
'LA ESCALERA SE ABRE AL CAER EL JEFE':'THE STAIRS OPEN WHEN THE BOSS FALLS',
'PISO COMPLETADO':'FLOOR COMPLETE',
'DESCENDIENDO...':'DESCENDING...',
'ÉLITE':'ELITE',
'MEJORAS PERMANENTES':'PERMANENT UPGRADES',
};
export default EN;