const EN:Record<string,string>={
'+1 corazón máximo. Bloquea el primer golpe de cada piso.':'+1 max heart. Blocks the first hit of each floor.',
'+15% crítico; más botín raro.':'+15% crit chance; more rare loot.',
'+30% velocidad de movimiento.':'+30% movement speed.',
'Un patito dispara 3 de daño cada 0.55 s.':'A duckling fires for 3 damage every 0.55 s.',
'Atrae monedas en un radio de 84 píxeles.':'Attracts coins within an 84-pixel radius.',
'+1 rebote de pared; los patitos ganan 2 más.':'+1 wall bounce; ducklings gain 2 more.',
'Cada quinto disparo hace +50% daño y quema.':'Every fifth shot deals +50% damage and burns.',
'+30% daño; enemigos +15% velocidad.':'+30% damage; enemies +15% speed.',
'Los enemigos tardan un 50% más en recargar.':'Enemies take 50% longer to reload.',
'El esquive deja humo: -35% velocidad enemiga, 2 s.':'Dash leaves smoke: -35% enemy speed for 2 s.',
'Aura: 3 de daño por segundo a enemigos cercanos.':'Aura: 3 damage per second to nearby enemies.',
'Los disparos atraviesan 1 enemigo más.':'Shots pierce 1 additional enemy.',
'+20% cadencia; +5% dispersión.':'+20% fire rate; +5% spread.',
'Absorbe un golpe de cualquier tipo por piso.':'Absorbs one hit of any kind per floor.',
'+20% de probabilidad de botín raro.':'+20% chance of rare loot.',
'Explosión cercana: 30 de daño.':'Nearby explosion: 30 damage.',
'Duplica la cadencia de disparo durante 6 s.':'Doubles fire rate for 6 s.',
'Una onda hace 15 de daño y empuja toda la sala.':'A wave deals 15 damage and pushes the whole room.',
'El gerente no autorizó esto.':'The manager did not authorize this.',
'PAN INFERNAL':'INFERNAL BREAD',
'IMÁN DORADO':'GOLDEN MAGNET',
'Más migas y vuelan directas hacia ti.':'More crumbs, and they fly straight to you.',
'CUAC ACUÁTICO':'AQUATIC QUACK',
'La onda CUAC incendia enemigos.':'The QUACK wave sets enemies on fire.',
'CÓMPLICE DOBLE':'DOUBLE ACCOMPLICE',
'El patito también duplica disparos.':'The duckling also doubles its shots.',
'Más distancia y salida invulnerable.':'More distance and invulnerability on exit.',
'PAN NUCLEAR':'NUCLEAR BREAD',
'Explosiones radiactivas más grandes.':'Larger radioactive explosions.',
'CAFÉ CON PLUMAS':'FEATHER COFFEE',
'La ametralladora gana 30% de cadencia adicional.':'The machine gun gains 30% additional fire rate.',
'El esquive causa 24 de daño al atravesar enemigos.':'Dash deals 24 damage when passing through enemies.',
'CUAC PEGAJOSO':'STICKY QUACK',
'El láser acumula el doble de lentitud.':'The laser stacks twice as much slow.',
'PAN FRANCÉS INFERNAL':'INFERNAL FRENCH BREAD',
'Los compañeros disparan más rápido; el guardaespaldas también dispara.':'Companions shoot faster; the bodyguard also shoots.',
'PAN TOSTADO':'TOAST',
'+1 daño.':'+1 damage.',
'Más duro. Más peligroso.':'Harder. More dangerous.',
'+1 rebote. Primer rebote: +20% daño.':'+1 bounce. First bounce: +20% damage.',
'Grasa táctica.':'Tactical grease.',
'+1 corazón máximo. -5% velocidad.':'+1 max heart. -5% speed.',
'Protección ovalada.':'Oval protection.',
'+2 daño.':'+2 damage.',
'PLUMA AERODINÁMICA':'AERODYNAMIC FEATHER',
'+15% velocidad de proyectil.':'+15% projectile speed.',
'+12% velocidad de movimiento.':'+12% movement speed.',
'PAN INTEGRAL':'WHOLE-WHEAT BREAD',
'La comida cura un 25% más.':'Food heals 25% more.',
'No preguntes qué crece.':'Don’t ask what grows.',
'SERVILLETA TÁCTICA':'TACTICAL NAPKIN',
'Bloquea el primer proyectil de cada sala.':'Blocks the first projectile in each room.',
'CASCO DE POLICÍA ROBADO':'STOLEN POLICE HELMET',
'-10% daño de contacto policial.':'-10% police contact damage.',
'Un préstamo sin permiso.':'A loan without permission.',
'+8% probabilidad de crítico.':'+8% critical-hit chance.',
'+10 migajas al comenzar cada piso.':'+10 crumbs at the start of each floor.',
'CASCARÓN REFORZADO':'REINFORCED SHELL',
'1 escudo por piso; bloquea daño de contacto.':'1 shield per floor; blocks contact damage.',
'Huevo con homologación.':'Certified egg.',
'PAN MOJADO':'WET BREAD',
'Los críticos queman durante 3 s.':'Critical hits burn for 3 s.',
'PAN CON MIEL':'HONEY BREAD',
'Curarte da +10% velocidad durante 5 s.':'Healing gives +10% speed for 5 s.',
'ALARMA DESCOMPUESTA':'BUSTED ALARM',
'+12% botín de mayor rareza en salas especiales.':'+12% higher-rarity loot in special rooms.',
'CUPÓN ROBADO':'STOLEN COUPON',
'Primera compra de cada piso: -25%.':'First purchase on each floor: -25%.',
'La policía vio un fantasma.':'The police saw a ghost.',
'Cada cuarto disparo añade dos proyectiles.':'Every fourth shot adds two projectiles.',
'PAN BENDITO':'BLESSED BREAD',
'Pan con trayectoria divina.':'Bread with a divine trajectory.',
'PATO DE BOLSILLO':'POCKET DUCK',
'Un patito dispara 4 de daño cada 0.8 s.':'A duckling fires for 4 damage every 0.8 s.',
'Pequeño cómplice.':'Tiny accomplice.',
'Dos patitos disparan 2 de daño cada 0.8 s.':'Two ducklings fire for 2 damage every 0.8 s.',
'Atraco familiar.':'A family heist.',
'El gerente también lo sabe.':'The manager knows it too.',
'CUAC RECARGADO':'RECHARGED QUACK',
'-25% tiempo de recarga del objeto activo.':'-25% active-item cooldown.',
'ULTRA CUAC':'ULTRA QUACK',
'Las ondas CUAC hacen 18 de daño extra.':'QUACK waves deal 18 extra damage.',
'PAN DE URANIO':'URANIUM BREAD',
'Balas grandes. +25% daño; -15% cadencia.':'Large bullets. +25% damage; -15% fire rate.',
'Los críticos tienen 35% de crear una migaja.':'Critical hits have a 35% chance to create a crumb.',
'CUAC INFINITO':'INFINITE QUACK',
'Cada baja reduce 0.5 s la recarga del objeto activo.':'Each kill reduces active-item cooldown by 0.5 s.',
'Las migajas cercanas orbitan y hacen 2 de daño.':'Nearby crumbs orbit and deal 2 damage.',
'ARMADURA DE BAGUETTE':'BAGUETTE ARMOR',
'1 escudo por piso. Al romperse, explota.':'1 shield per floor. When it breaks, it explodes.',
'GRANADA DE PAN':'BREAD GRENADE',
'Lanza una granada hacia la mira. Explota 0.8 s después de caer.':'Throws a grenade toward the cursor. Explodes 0.8 s after landing.',
'Pan con consecuencias.':'Bread with consequences.',
'PATITO SEÑUELO':'RUBBER DUCK DECOY',
'Aturde a todos los policías durante 4 s.':'Stuns all police for 4 s.',
'CAFÉ DOBLE':'DOUBLE COFFEE',
'+50% cadencia durante 6 s.':'+50% fire rate for 6 s.',
'Con un toque de pánico.':'With a touch of panic.',
'CAJA DE PAN':'BREAD BOX',
'El botiquín del panadero.':'The baker’s first-aid kit.',
'BOTÓN ROJO':'RED BUTTON',
'Efecto potente al azar. Puede activar la alarma.':'Powerful random effect. May trigger the alarm.',
'No pone qué hace.':'It doesn’t say what it does.',
'PAN BOMBA REMOTO':'REMOTE BREAD BOMB',
'Coloca un pan. Vuelve a usar para detonarlo.':'Places a loaf. Use again to detonate it.',
'ROCIADOR DE MANTEQUILLA':'BUTTER SPRAYER',
};
export default EN;