const EN:Record<string,string>={
'Rocía mantequilla hacia la mira. El piso se pone resbaloso.':'Sprays butter toward the cursor. The floor becomes slippery.',
'Cuidado con el piso.':'Watch your step.',
'MIGAJÓN DRON':'CRUMB DRONE',
'Un dron ataca 10 s al enemigo más cercano.':'A drone attacks the nearest enemy for 10 s.',
'PAN DE EMERGENCIA':'EMERGENCY BREAD',
'Recupera 2 de vida. No se usa con la vida llena.':'Restores 2 health. Cannot be used at full health.',
'El botiquín de verdad.':'The real first-aid kit.',
'Una alarma atrae enemigos 4 s y luego aturde.':'An alarm attracts enemies for 4 s, then stuns them.',
'Todos voltean para allá.':'Everyone looks over there.',
'Recupera 1 corazón.':'Restores 1 heart.',
'Botiquín con corteza.':'First aid with a crust.',
'Recupera 1 vida; +25% velocidad durante 6 s.':'Restores 1 health; +25% speed for 6 s.',
'BAGUETTE':'BAGUETTE',
'Recupera 3 de vida.':'Restores 3 health.',
'CROISSANT':'CROISSANT',
'Feliz cumpleaños, prófugo.':'Happy birthday, fugitive.',
'PAN DORADO':'GOLDEN BREAD',
'Rápido e imprevisible. No dejes que te rodee.':'Fast and unpredictable. Don’t let it surround you.',
'Avisa antes de disparar perdigones. Mantén tu distancia.':'Telegraphs before firing pellets. Keep your distance.',
'Bloquea por delante. Rodéalo durante su carga y recuperación.':'Blocks from the front. Circle around it during charge and recovery.',
'Sobrevuela obstáculos y dispara ráfagas.':'Flies over obstacles and fires bursts.',
'Persigue al pato sin descanso.':'Chases the duck relentlessly.',
'Rebota por la sala. Vigila su trayectoria.':'Bounces around the room. Watch its path.',
'Fija una mira durante 1 s antes de disparar. El tiro causa 2 de daño.':'Locks a sight for 1 s before firing. The shot deals 2 damage.',
'Cura aliados cercanos cada 2.5 s. Es débil cuando está solo.':'Heals nearby allies every 2.5 s. Weak when alone.',
'Aumenta la velocidad y cadencia de policías cercanos. Derrótalo primero.':'Boosts nearby police speed and fire rate. Defeat it first.',
'Anuncia su carga y queda vulnerable después. Es un ganso, no un perro.':'Telegraphs its charge and is vulnerable afterward. It’s a goose, not a dog.',
'ARMA · Cambia con la rueda':'WEAPON · Switch with the wheel',
'JEFE DE PISO · Botín garantizado':'FLOOR BOSS · Guaranteed loot',
'MINIJEFE · Riesgo y recompensa':'MINIBOSS · Risk and reward',
'SEGURIDAD DEL BANCO':'BANK SECURITY',
'Solo cambia tu estilo, nunca tus estadísticas.':'Only changes your style, never your stats.',
'Moneda de atraco':'Heist currency',
'APAGÓN':'BLACKOUT',
'ALARMA':'ALARM',
'PISO ENCERADO':'WAXED FLOOR',
'CÁMARAS ACTIVAS':'ACTIVE CAMERAS',
'BÓVEDA ABIERTA':'OPEN VAULT',
'Objeto recogido':'Item collected',
'Objeto disponible':'Item available',
'Sala despejada':'Room cleared',
'MAPA DEL BANCO':'BANK MAP',
'ESTÁS AQUÍ':'YOU ARE HERE',
'Ubicación segura':'Safe location',
'Tu sala actual':'Your current room',
'Solo orientación. Sin transporte.':'Navigation only. No fast travel.',
'Tienda':'Shop',
'Jefe':'Boss',
'Objeto':'Item',
'WASD / FLECHAS / MOUSE · INSPECCIONAR':'WASD / ARROWS / MOUSE · INSPECT',
'REEMPLAZAR ARMA':'REPLACE WEAPON',
'VIDA COMPLETA':'FULL HEALTH',
'ACÉRCATE PARA CURARTE':'MOVE CLOSER TO HEAL',
'DESAFÍO: SIN BONIFICACIÓN':'CHALLENGE: NO BONUS',
'DESAFÍO: SIN RECIBIR DAÑO':'CHALLENGE: NO DAMAGE TAKEN',
'NUEVA ARMA DESCUBIERTA':'NEW WEAPON DISCOVERED',
'NUEVO OBJETO DESCUBIERTO':'NEW ITEM DISCOVERED',
'ABRIR MAPA':'OPEN MAP',
'ATRACO PERFECTO':'PERFECT HEIST',
'¡AY!':'OUCH!',
'OBJETO ACTIVO ENCONTRADO':'ACTIVE ITEM FOUND',
'El objeto actual se soltará al suelo.':'Your current active item will be dropped on the floor.',
'SE BUSCA UN CÓMPLICE':'ACCOMPLICE WANTED',
'Cambiar arma':'Switch weapon',
'Abrir mapa':'Open map',
'FLECHAS / CLIC IZQUIERDO':'ARROWS / LEFT CLICK',
'El pan recupera vida. Las monedas doradas se guardan.':'Bread restores health. Golden coins are permanent.',
'Derrota al jefe, recoge el botín y baja al siguiente piso.':'Defeat the boss, collect the loot, and go to the next floor.',
'El mapa pausa el combate. No permite transportarte.':'The map pauses combat. It does not allow fast travel.',
'B · VOLVER':'B · BACK',
'ESC · VOLVER':'ESC · BACK',
'LA SEGURIDAD ES MÁS DURA AQUÍ':'SECURITY IS TOUGHER HERE',
'MAPA':'MAP',
'Mapa':'Map',
'NUEVO RÉCORD':'NEW RECORD',
'Encuéntralo durante un atraco para revelar su ficha.':'Find it during a heist to reveal its entry.',
'El banco aún guarda secretos.':'The bank is still hiding secrets.',
'POR DESCUBRIR':'UNDISCOVERED',
'DESCUBIERTOS':'DISCOVERED',
'CATEGORÍA':'CATEGORY',
'EXPLORAR':'BROWSE',
'DESPLAZAR':'SCROLL',
'PALANCA IZQUIERDA · MOVER  RT · DISPARAR  B · ESQUIVAR  A · INTERACTUAR  Y · OBJETO  VIEW · MAPA  START · PAUSA':'LEFT STICK · MOVE  RT · SHOOT  B · DASH  A · INTERACT  Y · ITEM  VIEW · MAP  START · PAUSE',
'W / S elegir · ENTER confirmar · rueda también vale':'W / S choose · ENTER confirm · mouse wheel also works',
'WASD mover · MOUSE / FLECHAS disparar · RUEDA cambiar arma · SHIFT esquivar · E interactuar · M mapa':'WASD move · MOUSE / ARROWS shoot · WHEEL switch weapon · SHIFT dash · E interact · M map',
'MAPA · Combate en pausa · WASD / FLECHAS / MOUSE inspeccionar · M / ESC cerrar':'MAP · Combat paused · WASD / ARROWS / MOUSE inspect · M / ESC close',
'ESC continuar · flechas navegar':'ESC resume · arrows navigate',
'ENTER confirmar · ESC volver':'ENTER confirm · ESC back',
'Pantalla completa · F':'Fullscreen · F',
'COMBATE EN PAUSA':'COMBAT PAUSED',
'✓ EQUIPADO':'✓ EQUIPPED',
'Paga 18 migajas por un objeto raro.':'Pay 18 crumbs for a rare item.',
'PANADERÍA CLANDESTINA':'UNDERGROUND BAKERY SHOP',
'Entrega 1 corazón por un objeto pasivo.':'Give 1 heart for a passive item.',
'DAR 1 CORAZÓN':'GIVE 1 HEART',
'MÁQUINA EXPENDEDORA':'VENDING MACHINE',
'PATO HERIDO':'INJURED DUCK',
'Dale 1 corazón. Te regala 8 monedas doradas.':'Give it 1 heart. It gives you 8 golden coins.',
'SALA DE INTERROGATORIO':'INTERROGATION ROOM',
'Paga 15 migajas o combate una patrulla élite.':'Pay 15 crumbs or fight an elite patrol.',
'Eso cayó de un camión.':'That fell off a truck.',
'El pan está caro.':'Bread is expensive.',
'Ese objeto no estaba aquí ayer.':'That item was not here yesterday.',
'ELIGE TU BOTÍN':'CHOOSE YOUR LOOT',
'SALA DE POLICÍAS':'POLICE ROOM',
'CÁMARAS DESACTIVADAS':'CAMERAS DISABLED',
};
export default EN;