const EN:Record<string,string>={
'¡REFUERZOS EN CAMINO!':'REINFORCEMENTS INCOMING!',
'Buena elección. Creo.':'Good choice. I think.',
'SALA PERFECTA':'PERFECT ROOM',
'OBJETO REPETIDO · +5 MIGAJAS':'DUPLICATE ITEM · +5 CRUMBS',
'¡BÓVEDA SECRETA!':'SECRET VAULT!',
'¡HOY NO!':'NOT TODAY!',
'¡PANDEMONIO!':'BREADLAM!',
'¡DIVIDENDOS!':'DIVIDENDS!',
'¡SALUD!':'HEALTH!',
'¡PREMIO GORDO!':'JACKPOT!',
'¡ERA LA ALARMA!':'IT WAS THE ALARM!',
'Una decisión prudente. Quizá.':'A sensible decision. Maybe.',
'El interrogatorio se complicó.':'The interrogation got complicated.',
'Necesitas más de un corazón.':'You need more than one heart.',
'Sin cambio. Con pan.':'No change. With bread.',
'Los cómplices no se olvidan.':'Accomplices are not forgotten.',
'No hemos visto ningún pato.':'We have not seen any duck.',
'¡Error bancario a tu favor!':'BANK ERROR IN YOUR FAVOR!',
'Solo devuelve 4 migajas. Típico.':'It only gives back 4 crumbs. Typical.',
'Si preguntan, ya venía vacía.':'If they ask, it was already empty.',
'PAN DE CAJA REFORZADO':'REINFORCED SANDWICH BREAD',
'+1 vida máxima.':'+1 max health.',
'Aprobada por ningún ingeniero.':'Approved by no engineer.',
'+15% velocidad de movimiento.':'+15% movement speed.',
'CAFÉ DEL OXXO':'CONVENIENCE-STORE COFFEE',
'+20% cadencia de disparo. -5% precisión.':'+20% fire rate. -5% accuracy.',
'Todavía se alcanza a leer.':'You can still read the label.',
'Primera compra de cada piso: -50%.':'First purchase on each floor: -50%.',
'El titular no está enterado.':'The cardholder has no idea.',
'Tras esquivar: +15% velocidad durante 2 s.':'After dashing: +15% speed for 2 s.',
'El primer golpe de cada sala causa 50% menos daño.':'The first hit in each room deals 50% less damage.',
'La moto se quedó afuera.':'The motorcycle stayed outside.',
'+8 migajas al entrar a cada piso.':'+8 crumbs when entering each floor.',
'Traía lunch y antecedentes.':'It came with lunch and a record.',
'PAN CON CHOCOLATE':'CHOCOLATE BREAD',
'Al recuperar vida: +20% daño durante 5 s.':'After healing: +20% damage for 5 s.',
'+1 penetración de proyectil.':'+1 projectile pierce.',
'+10% probabilidad de golpe crítico.':'+10% critical-hit chance.',
'Los golpes críticos tienen 20% de soltar una migaja.':'Critical hits have a 20% chance to drop a crumb.',
'Dejas charcos al caminar. Enemigos: -25% velocidad.':'You leave puddles while walking. Enemies: -25% speed.',
'El peor día, la mejor trampa.':'Worst day, best trap.',
'Atajada del año.':'Save of the year.',
'El recipiente sí se devuelve.':'The container is returnable.',
'+2 daño. -8% cadencia de disparo.':'+2 damage. -8% fire rate.',
'Arma blanca si le echas ganas.':'A melee weapon if you try hard enough.',
'Dice dónde está la salida. Casi.':'It says where the exit is. Almost.',
'Marca rutas conocidas a tienda, jefe y escaleras.':'Marks known routes to the shop, boss, and stairs.',
'MAPA MANCHADO':'STAINED MAP',
'Revela una sala especial al comenzar cada piso.':'Reveals one special room at the start of each floor.',
'Esperemos que sea café.':'Let us hope that is coffee.',
'Revela al jefe al despejar 60% de las salas normales.':'Reveals the boss after clearing 60% of normal rooms.',
'Ya se ve por dónde va el asunto.':'You can see where this is going.',
'SOPLÓN':'SNITCH',
'Revela la tienda. Sus precios suben 5%.':'Reveals the shop. Its prices increase by 5%.',
'La información cuesta.':'Information costs money.',
'Los golpes críticos interrumpen ataques durante 0.4 s.':'Critical hits interrupt attacks for 0.4 s.',
'Cada rebote aumenta el daño 20%, hasta +60%.':'Each bounce increases damage by 20%, up to +60%.',
'Se les resbaló el presupuesto.':'The budget slipped away.',
'El esquive causa 12 de daño a los enemigos que atraviesas.':'Dash deals 12 damage to enemies you pass through.',
'PAN QUEMADO':'BURNT BREAD',
'Cada impacto reduce 4% la velocidad; máximo 45%.':'Each hit reduces speed by 4%; max 45%.',
'Ahora sí, no te muevas.':'Now stay still.',
'Una baja crítica explota y causa 12 de daño cercano.':'A critical kill explodes and deals 12 nearby damage.',
'ALARMA PORTÁTIL':'PORTABLE ALARM',
'La discreción estaba sobrevalorada.':'Discretion was overrated.',
'BOLSA DE PAN':'BREAD BAG',
'Todavía viene calientito.':'It is still warm.',
'PATO DE LA SUERTE':'LUCKY DUCK',
'8% de sobrevivir un golpe mortal con media vida. Una vez.':'8% chance to survive a lethal hit at half health. Once.',
'CAÑÓN DOBLE':'DOUBLE CANNON',
'Duplica los proyectiles. Cada uno causa 70% del daño.':'Doubles projectiles. Each deals 70% damage.',
'Dos cañones, la misma mala idea.':'Two cannons, the same bad idea.',
'Dar vueltas también es una estrategia.':'Spinning around is also a strategy.',
'Un pollo dispara 5 de daño a policías cada segundo.':'A chicken deals 5 damage to police every second.',
'PATO GUARDAESPALDAS':'BODYGUARD DUCK',
'Un pato bloquea un proyectil cada 12 s.':'A duck blocks one projectile every 12 s.',
'Su contrato incluye pan.':'Its contract includes bread.',
'Armas explosivas: +40% área; -20% cadencia de disparo.':'Explosive weapons: +40% area; -20% fire rate.',
'Más pan del que puedes manejar.':'More bread than you can handle.',
'25% de dejar una zona dañina al derrotar enemigos.':'25% chance to leave a damaging zone after defeating enemies.',
'Brillan sin necesidad de lámpara.':'They glow without a lamp.',
'EL PAN PROHIBIDO':'FORBIDDEN BREAD',
'+50% daño. -2 vida máxima.':'+50% damage. -2 max health.',
'+5% daño por cada 25 migajas. Máximo +30%.':'+5% damage per 25 crumbs. Max +30%.',
'El rey también cuenta el cambio.':'Even the king counts the change.',
'Los tiempos de recarga avanzan 25% más rápido.':'Cooldowns progress 25% faster.',
'+30% daño. Precios de la tienda +30%.':'+30% damage. Shop prices +30%.',
'Hasta el daño paga intereses.':'Even damage pays interest.',
'PATO BUSCADO':'WANTED DUCK',
'+20% velocidad. +12% enemigos élite desde el piso 2.':'+20% speed. +12% elite enemies from floor 2.',
'Tu foto salió muy bien.':'Your photo came out great.',
'PAN CADUCADO':'EXPIRED BREAD',
'+25% cadencia de disparo. La comida cura 25% menos.':'+25% fire rate. Food heals 25% less.',
'El nivel de alerta aumenta 20% más lento.':'Alert level rises 20% more slowly.',
'Sí, esa foto es tuya.':'Yes, that is your photo.',
'ESPAÑOL':'SPANISH',
'ASPECTOS · CRUCETA PARA EXPLORAR     A · COMPRAR / EQUIPAR     B · VOLVER':'ASPECTS · D-PAD TO BROWSE     A · BUY / EQUIP     B · BACK',
'ASPECTOS · RUEDA DEL MOUSE PARA EXPLORAR     ENTER · COMPRAR / EQUIPAR     ESC · VOLVER':'ASPECTS · MOUSE WHEEL TO BROWSE     ENTER · BUY / EQUIP     ESC · BACK',
'LB / RB · CATEGORÍA     CRUCETA · EXPLORAR     B · VOLVER':'LB / RB · CATEGORY     D-PAD · BROWSE     B · BACK',
'A / D · CATEGORÍA     FLECHAS · EXPLORAR     RUEDA DEL MOUSE · DESPLAZAR     ESC · VOLVER':'A / D · CATEGORY     ARROWS · BROWSE     MOUSE WHEEL · SCROLL     ESC · BACK',
'Duck Heist. Usa WASD para moverte, flechas o clic izquierdo para disparar, clic derecho o Shift para esquivar, E para interactuar, M para el mapa y Escape para pausar.':'Duck Heist. Use WASD to move, arrows or left click to shoot, right click or Shift to dash, E to interact, M for the map, and Escape to pause.',
'E L   B A N C O   D E L   P A N':'T H E   B R E A D   B A N K',
'↑↓ elegir · ←→ cambiar · ESC volver':'↑↓ choose · ←→ change · ESC back',
'↑↓ elegir · ENTER comprar/equipar · ESC volver':'↑↓ choose · ENTER buy/equip · ESC back',
'ELIGE LA DIFICULTAD DEL ATRACO':'CHOOSE HEIST DIFFICULTY',
'Puedes cambiarla al comenzar cada nueva partida.':'You can change it at the start of each new run.',
'FÁCIL':'EASY',
'DIFÍCIL':'HARD',
'LOCO POR EL PAN':'BREAD MADNESS',
'Más margen para aprender. Enemigos más lentos y menos agresivos.':'More room to learn. Enemies are slower and less aggressive.',
'La experiencia actual de Duck Heist. Equilibrada y recomendada.':'The current Duck Heist experience. Balanced and recommended.',
'Más presión, enemigos más resistentes y ataques más frecuentes.':'More pressure, tougher enemies, and more frequent attacks.',
'El banco va a por ti. Máxima presión, más élites y casi sin respiro.':'The bank is coming for you. Maximum pressure, more elites, almost no breathing room.',
'RECOMENDADO':'RECOMMENDED',
'BLOQUEADO':'LOCKED',
'Completa un atraco para desbloquearlo.':'Complete a heist to unlock it.',
'W / S · ELEGIR     ENTER · CONFIRMAR     ESC · VOLVER':'W / S · CHOOSE     ENTER · CONFIRM     ESC · BACK',
'CRUCETA · ELEGIR     A · CONFIRMAR     B · VOLVER':'D-PAD · CHOOSE     A · CONFIRM     B · BACK',
'DIFICULTAD':'DIFFICULTY',
'W / S dificultad · ENTER confirmar · ESC volver':'W / S difficulty · ENTER confirm · ESC back',
'Cada rebote suma 15% de daño y acelera el patito.':'Each bounce adds 15% damage and speeds up the duck.',
'Mucho daño, lento y preciso':'High damage, slow and precise',
'Mantén la mira entre disparos: carga daño y probabilidad crítica.':'Keep aiming between shots to charge damage and critical chance.',
'Huevos que se rompen en tres yemas balísticas.':'Eggs that break into three ballistic yolks.',
'Al impactar o romperse, libera tres yemas en abanico.':'On impact or break, releases three yolks in a fan.',
'Francotirador de precisión y alto impacto.':'High-impact precision sniper.',
'Mantén la mira entre disparos para potenciar daño y crítico.':'Keep aiming between shots to boost damage and critical chance.',
'Corrige la trayectoria hacia el enemigo más cercano.':'Corrects its trajectory toward the nearest enemy.',
'PISTOLA DE MANTEQUILLA':'BUTTER BLASTER',
'Bolas de mantequilla que frenan al objetivo':'Butter blobs that slow the target',
'Cada impacto acumula lentitud. Rebota una vez en paredes.':'Each hit stacks slow. Bounces once off walls.',
'CORTACROISSANTS':'CROISSANT CUTTER',
'Dos medias lunas giratorias por disparo':'Two spinning crescents per shot',
'Cada hoja atraviesa un enemigo y rebota una vez.':'Each blade passes through one enemy and bounces once.',
'TALADRO DE BÓVEDA':'VAULT DRILL',
'Ráfaga perforante de alcance muy corto':'Very short-range piercing burst',
'DPS brutal de cerca. Atraviesa enemigos, pero exige arriesgarte.':'Brutal close-range DPS. Pierces enemies, but forces you to take risks.',
'TRITURADORA DE RECIBOS':'RECEIPT RIPPER',
'Escupe tiras de recibo en una ráfaga triple':'Fires receipt strips in a triple burst',
'Los recibos rebotan una vez y ganan daño al rebotar.':'Receipts bounce once and gain damage after bouncing.',
};
Object.assign(EN,{
'PICO PERCUTOR':'BEAK PERCUTOR','Pistola precisa de tres tiempos.':'Precise three-beat pistol.','Cada tercer disparo atraviesa un objetivo y golpea más fuerte.':'Every third shot pierces one target and hits harder.','NÓMINA .42':'PAYROLL .42','Revólver contable de alta precisión.':'High-precision accounting revolver.','Probabilidad crítica elevada. Los críticos pueden soltar una migaja.':'Higher critical chance. Critical hits can drop a crumb.','GOMERA DE MIGAS':'CRUMB SLINGSHOT','Migas endurecidas lanzadas con liga industrial.':'Hardened crumbs launched with industrial elastic.','Rebota dos veces y gana daño con cada pared.':'Bounces twice and gains damage with each wall hit.','PISTOLA DE JARABE':'SYRUP PISTOL','Munición pegajosa para controlar pasillos.':'Sticky ammunition for controlling corridors.','Cada impacto frena al enemigo durante unos segundos.':'Each hit slows the enemy for a few seconds.','PAGA-PATOS':'DUCK PAYOUT','Arma financiera que dispara fichas de bóveda.':'Financial weapon that fires vault chips.','Hace hasta 30% más daño según las migajas que cargas.':'Deals up to 30% more damage based on the crumbs you carry.','TRONADOR DE COSTRA':'CRUST THUNDERER','Escopeta pesada de pan horneado.':'Heavy baked-bread shotgun.','Gran retroceso y devastación a quemarropa.':'Heavy recoil and point-blank devastation.','HORNO RECORTADO':'SAWN-OFF OVEN','Dos bocas, una pésima idea.':'Two barrels, one terrible idea.','Dispara diez fragmentos muy juntos con una pausa larga.':'Fires ten tightly packed fragments with a long pause.','MOLINILLO DE PAN':'BREAD GRINDER','Convierte la panadería en metralla.':'Turns the bakery into shrapnel.','Abanico enorme de migas de alcance corto.':'Huge spread of short-range crumbs.','ESCOPETA DE MERMELADA':'JAM SHOTGUN','Perdigones dulces y extremadamente pegajosos.':'Sweet and extremely sticky pellets.','Los impactos ralentizan; varios perdigones acumulan el efecto.':'Hits slow targets; multiple pellets stack the effect.','RÁFAGA DE HARINA':'FLOUR BURST','Ametralladora ligera que llena la sala de polvo.':'Light machine gun that fills the room with flour dust.','Cadencia altísima; compensa el daño bajo con volumen de fuego.':'Very high fire rate; makes up for low damage with volume of fire.','SUBCUAC 9':'SUBQUACK 9','Subfusil compacto para atracos apresurados.':'Compact SMG for rushed heists.','Rápida, estable y fiable mientras te mueves.':'Fast, stable, and reliable while moving.','PICOTEADORA TÁCTICA':'TACTICAL PECKER','Ráfagas compactas de tres proyectiles.':'Compact three-projectile bursts.','Tres disparos casi paralelos para castigar blancos medianos.':'Three nearly parallel shots for punishing mid-range targets.','VENTILADOR DE SERVILLETAS':'NAPKIN FAN','Lanza papel afilado en abanico.':'Throws sharpened paper in a fan.','Siete hojas cubren una zona enorme y una puede atravesar.':'Seven sheets cover a huge area and one can pierce.','CINTA TRANSPORTADORA':'CONVEYOR BELT','Cadena industrial de disparos consecutivos.':'Industrial chain of consecutive shots.','Cada quinto disparo acelera y pega más fuerte.':'Every fifth shot flies faster and hits harder.','MORTERO DE MASA':'DOUGH MORTAR','Bolas de masa explosiva de gran radio.':'Large-radius explosive dough balls.','Lento y pesado; limpia grupos sin exigir puntería perfecta.':'Slow and heavy; clears groups without requiring perfect aim.','GRAN BAGUETÓN':'MEGA BAGUETTE','Una baguette absurda con propulsión propia.':'An absurd baguette with its own propulsion.','Explosión enorme, mucho empujón y cadencia muy lenta.':'Huge explosion, massive knockback, and a very slow fire rate.','CAZUELA VOLÁTIL':'VOLATILE PAN','Recipiente blindado relleno de masa reactiva.':'Armored pan filled with reactive dough.','Rebota una vez; el rebote aumenta el daño antes de explotar.':'Bounces once; the bounce increases damage before it explodes.','COHETE DE CROQUETA':'CROQUETTE ROCKET','Proyectil rápido con una pequeña carga explosiva.':'Fast projectile with a compact explosive charge.','Mucho más veloz que otros explosivos; radio compacto.':'Much faster than other explosives; compact blast radius.','CAÑÓN DE LEVADURA':'YEAST CANNON','Masa expansiva que despeja espacio.':'Expanding dough that clears space.','La explosión empuja con fuerza a los supervivientes.':'The explosion strongly pushes surviving enemies away.','RAYO DE MOSTAZA':'MUSTARD RAY','Haz corrosivo amarillo de alcance medio.':'Corrosive yellow mid-range beam.','Atraviesa y ralentiza a todo lo que toca.':'Pierces and slows everything it touches.','BOBINA DE PAN CUÁNTICO':'QUANTUM BREAD COIL','Descarga experimental entre objetivos cercanos.':'Experimental discharge between nearby targets.','Al impactar, salta a otro enemigo con daño reducido.':'On hit, arcs to another enemy for reduced damage.','ARCO DE TOSTADO':'TOAST ARC','Electricidad de cocina mal aislada.':'Poorly insulated kitchen electricity.','El impacto encadena dos descargas pequeñas a enemigos próximos.':'The impact chains two smaller shocks to nearby enemies.','PROYECTOR DE MIGAJA NEGRA':'BLACK CRUMB PROJECTOR','Dispara una miga imposible que curva el espacio.':'Fires an impossible crumb that bends space.','Mientras viaja atrae enemigos cercanos hacia su trayectoria.':'While traveling, it pulls nearby enemies toward its path.','SINTETIZADOR DE CUAC':'QUACK SYNTHESIZER','Convierte un cuac en una pared de presión.':'Turns a quack into a wall of pressure.','Cinco ondas perforantes empujan grupos completos.':'Five piercing waves push entire groups.','PARAGUAS BALÍSTICO':'BALLISTIC UMBRELLA','Seguridad bancaria en todas direcciones.':'Bank security in every direction.','Dispara ocho proyectiles alrededor del pato sin importar la mira.':'Fires eight projectiles around the duck regardless of aim.','CAJA REGISTRADORA':'CASH REGISTER','Tickets, cambio y mala contabilidad.':'Receipts, change, and terrible accounting.','Las bajas tienen probabilidad de soltar una migaja extra.':'Kills have a chance to drop an extra crumb.','IMPRESORA DE MULTAS':'FINE PRINTER','Papel oficial a velocidades poco oficiales.':'Official paper at very unofficial speeds.','Tiras veloces atraviesan hasta dos enemigos.':'Fast strips pierce up to two enemies.','RODILLO DE COCINA':'KITCHEN ROLLING PIN','No todo atraco necesita balas.':'Not every heist needs bullets.','Golpe frontal de alcance mínimo, daño enorme y empujón brutal.':'Minimal-range frontal strike with huge damage and brutal knockback.','IMÁN DE BÓVEDA':'VAULT MAGNET','Campo magnético portátil de procedencia dudosa.':'Portable magnetic field of questionable origin.','El orbe desvía y puede devolver proyectiles enemigos cercanos.':'The orb bends and can return nearby enemy projectiles.','PATO DE GOMA ORBITAL':'ORBITAL RUBBER DUCK','Patitos tácticos que primero protegen y luego cazan.':'Tactical ducklings that protect first and hunt later.','Orbita brevemente alrededor de ti y después busca un enemigo.':'Briefly orbits you, then seeks an enemy.','Armadura espacial verde, visor ámbar y cero preguntas sobre la misión.':'Green space armor, amber visor, and zero questions about the mission.'
});
Object.assign(EN,{'PEDESTAL DE SEGURIDAD':'SECURITY PEDESTAL','12 migajas: reduce la alerta y revela al jefe del piso.':'12 crumbs: lowers alert and reveals the floor boss.','INTERVENIR · 12':'INTERVENE · 12','DEJARLO':'LEAVE IT','PEDESTAL MÉDICO':'MEDICAL PEDESTAL','10 migajas: recupera 1 corazón si estás herido.':'10 crumbs: restores 1 heart if you are injured.','CURAR · 10':'HEAL · 10','PEDESTAL DEL ARSENAL':'ARSENAL PEDESTAL','24 migajas: fabrica un arma aleatoria para recoger.':'24 crumbs: builds a random weapon to pick up.','FABRICAR · 24':'BUILD · 24','ALTAR DE LA MIGA':'CRUMB ALTAR','Entrega 1 corazón por una recompensa de jefe.':'Give 1 heart for a boss reward.','OFRECER 1 CORAZÓN':'OFFER 1 HEART','ALEJARSE':'WALK AWAY','Ya estás al máximo.':'You are already at full health.','Cámaras anuladas. Objetivo localizado.':'Cameras disabled. Target located.','Vendaje rápido. Nada de preguntas.':'Quick bandage. No questions asked.','El arsenal imprimió algo ilegal.':'The arsenal printed something illegal.','La miga aceptó el trato.':'The crumb accepted the deal.'});
Object.assign(EN,{'CAMIONETA DEL MERCADO NEGRO':'BLACK MARKET VAN','CAMIONETA':'VAN','EL PROVEEDOR':'THE SUPPLIER','Tres fierros. Cero preguntas.':'Three guns. No questions.','La camioneta no existe.':'The van does not exist.','Mira rápido y paga en migajas.':'Look fast and pay in crumbs.','No preguntes de dónde salieron.':'Do not ask where they came from.','Armadura verde de asalto espacial, casco reforzado y visor dorado.':'Green space-assault armor, reinforced helmet, and golden visor.'});
Object.assign(EN,{'BARISTA MIGAJÓN':'BARISTA CRUMB','Calientito y sin preguntas.':'Warm and no questions asked.'});
Object.assign(EN,{'CURSOR':'CURSOR','CLÁSICO':'CLASSIC','PUNTO':'DOT','CRUZ TÁCTICA':'TACTICAL CROSS','CUAC':'QUACK','MIGA':'CRUMB','PAN':'BREAD','MONEDA':'COIN','DIAMANTE':'DIAMOND','HUEVO':'EGG','PLUMA':'FEATHER','BÓVEDA':'VAULT','CALAVERA':'SKULL','BOCINA · SILENCIAR TODO':'SPEAKER · MUTE ALL','SONIDO SILENCIADO · CLIC EN LA BOCINA PARA ACTIVAR':'SOUND MUTED · CLICK SPEAKER TO RESTORE','FLECHAS · AJUSTAR     CLIC · ELEGIR NIVEL     M · SILENCIAR     ESC · VOLVER':'ARROWS · ADJUST     CLICK · SET LEVEL     M · MUTE     ESC · BACK','CRUCETA · AJUSTAR     A · CAMBIAR     B · VOLVER':'D-PAD · ADJUST     A · CHANGE     B · BACK'});
Object.assign(EN,{'EVENTO DE ALTO RIESGO':'HIGH-RISK EVENT','EVENTO SUPERADO':'EVENT CLEARED','Primero sobrevive al operativo.':'Survive the security operation first.'});
export default EN;