import{copyFileSync,readFileSync,writeFileSync,mkdirSync}from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';const here=path.dirname(fileURLToPath(import.meta.url));
const edit=(f,fn)=>{const s=readFileSync(f,'utf8'),n=fn(s);if(n===s)throw new Error('Localization patch failed: '+f);writeFileSync(f,n)};
export function applyDuckLocalization(g){const l=path.join(g,'localization');mkdirSync(l,{recursive:true});for(const f of ['runtime.ts','en.ts','en1.ts','en2.ts','en3.ts','en4.ts','en5.ts','en6.ts'])copyFileSync(path.join(here,f),path.join(l,f));
edit(path.join(g,'game/ui.ts'),s=>s.replace("import { drawPixelLogo } from './titleScene';","import { drawPixelLogo } from './titleScene';\nimport { translateText } from '../localization/runtime';").replace(/\) \{\n  ctx\.save\(\);\n  ctx\.font = `\$\{strong \? '700' : '600'\} \$\{size\}px \$\{FONT_UI\}`;/,") {\n  str=translateText(str);\n  ctx.save();\n  ctx.font = `${strong ? '700' : '600'} ${size}px ${FONT_UI}`;").replace(/(export function titleText\([\s\S]*?\) \{)\n  ctx\.save\(\);/,'$1\n  str=translateText(str);\n  ctx.save();').replace(/(export function wrappedText\([^\n]+\) \{)\n  ctx\.save\(\);/,'$1\n  str=translateText(str);\n  ctx.save();').replace(/(export function pixelText\([^\n]+\) \{)\n  ctx\.save\(\);/,'$1\n  str=translateText(str);\n  ctx.save();'));
edit(path.join(g,'game/engine.ts'),s=>s.replace("import { T } from './i18n';","import { T } from './i18n';\nimport { getLocale,setLocale } from '../localization/runtime';").replace(/export const SETTING_ROWS = \[[\s\S]*?\n\];/,`export const SETTING_ROWS = [
  {key:'language',label:'IDIOMA',kind:'language' as const},
  {key:'master',get label(){return T.settingMaster},kind:'vol' as const},
  {key:'music',get label(){return T.settingMusic},kind:'vol' as const},
  {key:'sfx',get label(){return T.settingSfx},kind:'vol' as const},
  {key:'shake',get label(){return T.settingShake},kind:'shake' as const},
  {key:'damageNumbers',get label(){return T.settingDamage},kind:'bool' as const},
  {key:'uiScale',get label(){return T.settingUiScale},kind:'scale' as const},
  {key:'fullscreen',get label(){return T.settingFullscreen},kind:'bool' as const},
  {key:'brightness',label:'BRILLO',kind:'brightness' as const},{key:'testQuack',label:'PROBAR CUAC',kind:'action' as const},{key:'testDash',label:'PROBAR ESQUIVE',kind:'action' as const},
];`).replace("  if (!row || row.kind === 'action') return 0;","  if (!row || row.kind === 'action') return 0;\n  if(row.kind==='language')return getLocale()==='en-US'?1:0;").replace("  if (!row) return;\n  if (row.key === 'testQuack') {","  if (!row) return;\n  if(row.kind==='language'){setLocale(getLocale()==='en-US'?'es-MX':'en-US');playUiMove();engine.onStateChange?.(engine.state);return;}\n  if (row.key === 'testQuack') {"));
edit(path.join(g,'game/render.ts'),s=>s.replace("import { T, FLOOR_NAMES_ES } from './i18n';","import { T, FLOOR_NAMES_ES } from './i18n';\nimport { translateText } from '../localization/runtime';").replace("function prompt(ctx: CanvasRenderingContext2D, x: number, y: number, label: string, color = '#f4d03f') {\n  ctx.save();","function prompt(ctx: CanvasRenderingContext2D, x: number, y: number, label: string, color = '#f4d03f') {\n  label=translateText(label);\n  ctx.save();").replace("    if (row.kind === 'vol' || row.kind === 'shake' || row.kind === 'scale' || row.kind==='brightness') {\n      const max = row.kind === 'vol' ? 1 : row.kind === 'shake' ? 2 : row.kind==='brightness'?1.4:3;\n      drawBar(ctx,320,y+6,60,v/max,on?'#f4d03f':'#5c6472');\n      text(ctx,row.kind==='vol'?`${Math.round(v*100)}%`:`${v}`,405,y+13,8,on?'#fff6c9':'#8792a5','right');\n    } else {\n      text(ctx,row.kind==='action'?'REPRODUCIR':v>.5?T.on:T.off,405,y+13,8,v>.5?'#39d353':'#b5c2b7','right',true);\n    }","    if(row.kind==='language') text(ctx,v>.5?'ENGLISH':'ESPAÑOL',405,y+13,8,'#f4d03f','right',true);\n    else if(row.kind==='vol'||row.kind==='shake'||row.kind==='scale'||row.kind==='brightness'){const max=row.kind==='vol'?1:row.kind==='shake'?2:row.kind==='brightness'?1.4:3;drawBar(ctx,320,y+6,60,v/max,on?'#f4d03f':'#5c6472');text(ctx,row.kind==='vol'?(Math.round(v*100)+'%'):String(v),405,y+13,8,on?'#fff6c9':'#8792a5','right');}\n    else text(ctx,row.kind==='action'?'REPRODUCIR':v>.5?T.on:T.off,405,y+13,8,v>.5?'#39d353':'#b5c2b7','right',true);"));
edit(path.join(g,'game/layout.ts'),s=>s.replace("export const SETTINGS = { x:62,y:63,w:356,h:20,gap:5 };","export const SETTINGS = { x:62,y:63,w:356,h:18,gap:3 };"));
edit(path.join(g,'App.tsx'),s=>s.replace("import { runSelfChecks, type CheckReport } from './game/selftest';","import { runSelfChecks, type CheckReport } from './game/selftest';\nimport { translateText } from './localization/runtime';").replace('aria-label="Duck Heist. Usa WASD para moverte, flechas o clic izquierdo para disparar, clic derecho o Shift para esquivar, E para interactuar, M para el mapa y Escape para pausar."',"aria-label={translateText('Duck Heist. Usa WASD para moverte, flechas o clic izquierdo para disparar, clic derecho o Shift para esquivar, E para interactuar, M para el mapa y Escape para pausar.')}").replace('          Pantalla completa · F\n',"          {translateText('Pantalla completa · F')}\n").replace(/return 'PALANCA IZQUIERDA[^']*';/,m=>`return translateText(${JSON.stringify(m.slice(8,-2))});`).replace(/case GameState\.MENU: return '([^']*)';/,"case GameState.MENU: return translateText('$1');").replace(/case GameState\.PLAYING: return '([^']*)';/,"case GameState.PLAYING: return translateText('$1');").replace(/case GameState\.MAP:return '([^']*)';/,"case GameState.MAP:return translateText('$1');").replace(/case GameState\.PAUSED: return '([^']*)';/,"case GameState.PAUSED: return translateText('$1');").replace(/default: return '([^']*)';/,"default: return translateText('$1');"));}