import{readFileSync,writeFileSync}from'node:fs';import path from'node:path';
const renameFn=(src,name)=>{const re=new RegExp('function\\s+'+name+'\\s*\\(');if(!re.test(src))return{src,found:false};return{src:src.replace(re,m=>m.replace(name,name+'Legacy')),found:true};};
const HELPERS=`type DHMenuMode='menu'|'difficulty'|'pause'|'death'|'victory'|'upgrades'|'wardrobe'|'collection'|'how'|'settings';
function dhAccent(mode:DHMenuMode){if(mode==='death')return'#ff6258';if(mode==='victory')return'#6fe28a';if(mode==='pause')return'#91b8c8';if(mode==='collection')return'#8fb4d8';if(mode==='how')return'#9bc7c2';return'#f4d03f';}
function dhGlyph(ctx:CanvasRenderingContext2D,mode:DHMenuMode,x:number,y:number,col:string){ctx.save();ctx.fillStyle=col;const p=(a:number,b:number,w:number,h:number)=>ctx.fillRect(x+a,y+b,w,h);if(mode==='menu'){p(1,1,10,10);ctx.fillStyle='#0b111b';p(3,3,6,6);ctx.fillStyle=col;p(5,2,2,8);p(2,5,8,2);p(5,5,2,2);}else if(mode==='difficulty'){p(1,8,2,3);p(5,5,2,6);p(9,2,2,9);}else if(mode==='pause'){p(2,1,3,10);p(7,1,3,10);}else if(mode==='death'){p(2,1,2,2);p(8,1,2,2);p(4,3,4,2);p(1,5,10,4);p(3,9,2,2);p(7,9,2,2);ctx.fillStyle='#0b111b';p(3,6,2,2);p(7,6,2,2);}else if(mode==='victory'){p(1,8,10,3);p(2,4,2,4);p(5,2,2,6);p(8,4,2,4);p(1,2,2,2);p(9,2,2,2);}else if(mode==='upgrades'){p(5,1,2,10);p(2,4,8,2);p(3,2,6,2);}else if(mode==='wardrobe'){p(4,1,4,2);p(2,3,8,2);p(1,5,3,6);p(8,5,3,6);p(4,5,4,6);}else if(mode==='collection'){p(1,2,4,4);p(7,2,4,4);p(1,8,4,3);p(7,8,4,3);}else if(mode==='how'){p(1,2,10,8);ctx.fillStyle='#0b111b';p(3,4,2,2);p(7,4,2,2);p(5,7,2,2);}else{p(5,1,2,10);p(1,5,10,2);p(3,3,6,6);ctx.fillStyle='#0b111b';p(5,5,2,2);}ctx.restore();}
function dhChrome(engine:GameEngine,mode:DHMenuMode){const ctx=engine.ui!,a=dhAccent(mode),m='#33404e';ctx.save();ctx.imageSmoothingEnabled=false;ctx.fillStyle='rgba(3,7,12,.88)';ctx.fillRect(11,7,CANVAS_WIDTH-22,2);ctx.fillRect(11,CANVAS_HEIGHT-9,CANVAS_WIDTH-22,2);ctx.fillStyle=a;ctx.fillRect(16,8,CANVAS_WIDTH-32,1);ctx.fillRect(12,12,1,CANVAS_HEIGHT-24);ctx.fillRect(CANVAS_WIDTH-13,12,1,CANVAS_HEIGHT-24);ctx.fillRect(12,8,6,4);ctx.fillRect(CANVAS_WIDTH-18,8,6,4);ctx.fillRect(12,CANVAS_HEIGHT-12,6,4);ctx.fillRect(CANVAS_WIDTH-18,CANVAS_HEIGHT-12,6,4);ctx.fillStyle=m;for(let y=30;y<CANVAS_HEIGHT-28;y+=28){ctx.fillRect(9,y,3,2);ctx.fillRect(CANVAS_WIDTH-12,y,3,2);}ctx.fillStyle=a;ctx.fillRect(21,14,4,2);ctx.fillRect(27,14,2,2);ctx.fillRect(31,14,2,2);dhGlyph(ctx,mode,CANVAS_WIDTH-35,14,a);if(mode==='death'){for(let x=42;x<CANVAS_WIDTH-42;x+=16){ctx.fillStyle=((x/16)%2|0)?'#9e343b':'#375f9d';ctx.fillRect(x,8,8,2);}}if(mode==='settings'){const y=SETTINGS.y+engine.settingsIndex*(SETTINGS.h+SETTINGS.gap);ctx.strokeStyle=a;ctx.strokeRect(SETTINGS.x-.5,y-.5,SETTINGS.w+1,SETTINGS.h+1);ctx.fillStyle=a;ctx.fillRect(SETTINGS.x-5,y+4,3,Math.max(4,SETTINGS.h-8));}ctx.restore();}
`;
const BUTTON_WRAP=`function drawButtons(ctx:CanvasRenderingContext2D,buttons:any[],selected:number,cx:number,top:number,_frame:number,w?:number,h?:number,gap?:number,...rest:any[]){(drawButtonsLegacy as any)(ctx,buttons,selected,cx,top,_frame,w,h,gap,...rest);if(!buttons?.length)return;const ww=w??200,hh=h??22,gg=gap??4,i=Math.max(0,Math.min(buttons.length-1,selected)),x=Math.round(cx-ww/2),y=Math.round(top+i*(hh+gg));ctx.save();ctx.imageSmoothingEnabled=false;ctx.strokeStyle='#f4d03f';ctx.strokeRect(x-.5,y-.5,ww+1,hh+1);ctx.fillStyle='#f4d03f';ctx.fillRect(x-5,y+4,3,Math.max(4,hh-8));ctx.fillRect(x+3,y+3,5,2);ctx.fillRect(x+3,y+hh-5,5,2);ctx.fillRect(x+ww-8,y+3,5,2);ctx.fillRect(x+ww-8,y+hh-5,5,2);ctx.fillStyle='#fff0a6';ctx.fillRect(x+ww-5,y+Math.max(4,Math.floor(hh/2)-1),3,3);ctx.restore();}
`;
export function applyDuckMenuOverhaul(gameDir){const file=path.join(gameDir,'game','render.ts');let r=readFileSync(file,'utf8'),wrap='';const screens=[['renderMenuUI','menu'],['renderDifficultyUI','difficulty'],['renderPausedUI','pause'],['renderGameOverUI','death'],['renderVictoryUI','victory'],['renderUpgradesUI','upgrades'],['renderWardrobeUI','wardrobe'],['renderCollectionUI','collection'],['renderHowToPlayUI','how'],['renderHowToPlay','how'],['renderSettingsUI','settings']];for(const [name,mode]of screens){const q=renameFn(r,name);r=q.src;if(q.found)wrap+=`function ${name}(engine:GameEngine){${name}Legacy(engine);dhChrome(engine,'${mode}' as DHMenuMode);}\n`;}const b=renameFn(r,'drawButtons');r=b.src;r+='\n'+HELPERS+'\n'+(b.found?BUTTON_WRAP:'')+'\n'+wrap;writeFileSync(file,r);}
